### ISSUE TITLE
Out of memory traceback is not handled

### ISSUE THREAD

**Issue by iranzo** [sosreport/sos#1317]
~~~
Creating compressed archive...
[archive:TarFileArchive] An error occurred compressing the archive:  [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/sbin/sosreport", line 25, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1637, in main
    sos.execute()
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1616, in execute
    return self.final_work()
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1529, in final_work
    checksum = self._create_checksum(archive, hash_name)
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1469, in _create_checksum
    digest.update(archive_fp.read())
MemoryError
~~~

**Comment by jcastill** [comment]
@iranzo I'm working on a patch for this, but I cannot reproduce. Do you have some steps I can follow?

**Comment by iranzo** [comment]
No sorry, if I recall it correctly the problem was a system with lot of ram in use (reserved) for hugepages, that caused sos to traceback

Speaking with Bryn, he suggested to raise this to catch it in a proper way (we had several customers doing over-allocation of hugepages that left the system in unusable status)

**Comment by bmr-cymru** [comment]
Make a giant list comprehension in a plugin? Use range or something to generate an obscene number of entries.

**Comment by bmr-cymru** [comment]
(this always worked well in `bash`)
