### ISSUE TITLE
[archive] Race error when more plugins create same dir concurrently

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1340]
When running sosreport with many threads, `OSError: [Errno 17] File exists:` may happen with below backtrace:

    Traceback (most recent call last):
      File "/root/sos-master/sos/sosreport.py", line 1320, in collect_plugin
        plug.collect()
      File "/root/sos-master/sos/plugins/__init__.py", line 940, in collect
        self._collect_copy_specs()
      File "/root/sos-master/sos/plugins/__init__.py", line 898, in _collect_copy_specs
        self._do_copy_path(path)
      File "/root/sos-master/sos/plugins/__init__.py", line 454, in _do_copy_path
        self.archive.add_file(srcpath, dest)
      File "/root/sos-master/sos/archive.py", line 160, in add_file
        self._check_path(dest)
      File "/root/sos-master/sos/archive.py", line 154, in _check_path
        self._makedirs(dest_dir)
      File "/root/sos-master/sos/archive.py", line 249, in _makedirs
        os.makedirs(path, mode)
      File "/usr/lib64/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 17] File exists: '/var/tmp/sos.WPqhH1/sosreport-pmoravec-rhel74-2018-06-11-efmcqum/proc'

`archive` should catch this error around `os.makedirs` call (or rather in `makedirs`?).

**Comment by bmr-cymru** [comment]
I think the problem is a bit deeper than that: the race occurred here:

```python
149     def _check_path(self, dest):
150         dest_dir = os.path.split(dest)[0]
151         if not dest_dir:
152             return
153         if not os.path.isdir(dest_dir):
154             self._makedirs(dest_dir)
```

For the backtrace above, the `isdir()` call on 153 must have failed, and the directory must have been created in another thread by the time we reached the `os.makerdirs()` call in the function called on line 154.

I suppose in this case we can catch the `OSError`, as long as it is `File Exists`: this should never be harmful (so long as it is also a directory - if it were a regular or other file type that would cause lots more errors down the line and needs to be reported since it indicates a bug).

The other alternative is to add locking to the archive class so that operations that modify the structure of the archive namespace are serialised wrt one another.
