### ISSUE TITLE
[archive] _check_path raises "not a regular file" for tailed symlink to reg.file

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1376]
A bit artificial execution of `sosreport` reported quite valid issue:

    $ cat sos_logs/satellite-plugin-errors.txt 
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1088, in collect_plugin
        plug.collect()
      File "/usr/lib/python2.7/site-packages/sos/plugins/__init__.py", line 947, in collect
        self._collect_copy_specs()
      File "/usr/lib/python2.7/site-packages/sos/plugins/__init__.py", line 905, in _collect_copy_specs
        self._do_copy_path(path)
      File "/usr/lib/python2.7/site-packages/sos/plugins/__init__.py", line 435, in _do_copy_path
        self._copy_dir(srcpath)
      File "/usr/lib/python2.7/site-packages/sos/plugins/__init__.py", line 381, in _copy_dir
        self._do_copy_path(os.path.join(srcpath, afile), dest=None)
      File "/usr/lib/python2.7/site-packages/sos/plugins/__init__.py", line 454, in _do_copy_path
        self.archive.add_file(srcpath, dest)
      File "/usr/lib/python2.7/site-packages/sos/archive.py", line 237, in add_file
        dest = self._check_path(dest, P_FILE)
      File "/usr/lib/python2.7/site-packages/sos/archive.py", line 221, in _check_path
        raise ValueError(ve_msg % (dest, "regular file"))
    ValueError: path '/var/tmp/sos.k9YH04/sosreport-pmoravec-sat63-2018-07-03-uztctia/var/log/httpd/foreman-ssl_access_ssl.log-20180624' exists and is not a regular file
    $

Because:

    $ file ./var/log/httpd/foreman-ssl_access_ssl.log-20180624
./var/log/httpd/foreman-ssl_access_ssl.log-20180624: symbolic link to `../../../sos_strings/apache/var.log.httpd.foreman-ssl_access_ssl.log-20180624.tailed'
    $

The `_check_path` routine should properly detect cases when another plugin asked to collect the same file to be checked now, but the file was tailed due to sizelimit and symbolic link is created instead.

**Comment by TurboTurtle** [comment]
Is it sufficient for us to add a secondary check that if it is a symlink to within the archive, to just skip the additional collection? I'm thinking yes, but I'm not sure of corner cases where we'd still want to raise an exception.

**Comment by pmoravec** [comment]
We do prevent such issues one by one, like here by disabling `apache` plugin to collect `/var/log/httpd/foreman` logs. But that secondary check (probably followed by a warning message?) sounds good to me.

**Comment by TurboTurtle** [comment]
I've cycled back around looking at this, and it folds into the "allow multiple plugins to specify the same file" issue that we've had for a bit. That being said, that particular issue is proving to be more intricate than I initially thought - mainly due to the fact that tailing file collections that are over a sizelimit happens during `setup()`, which presents an issue when trying to detect existing collections from other plugins that could occur in either `setup()` or `collect()`.

Thus, this also plays into the discussion we've been having internally at RH about potentially opening up plugins to allow for "manual" collections - i.e. those that are not simple command executions or iterations.

I believe this would best be solved by moving the actual string collections to `collect()` fully. At that point, `check_path()` can be updated to include logic to check for previous collections with a different sizelimit, and be confident in the fact that the collections are occurring within the same phase, so that we don't need to contend with artificial race conditions.
