### ISSUE TITLE
[archive] exception when adding not-tailed file after the file was added as tailed

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1596]
Reproducer: enable `apache` and `satellite` plugins with `-a` option to let them both collect `/var/log/httpd`. `satellite` plugin then raises:

    Traceback (most recent call last):
      File "/root/sos-master/sos/sosreport.py", line 1123, in collect_plugin
        plug.collect()
      File "/root/sos-master/sos/plugins/__init__.py", line 1009, in collect
        self._collect_copy_specs()
      File "/root/sos-master/sos/plugins/__init__.py", line 965, in _collect_copy_specs
        self._do_copy_path(path)
      File "/root/sos-master/sos/plugins/__init__.py", line 503, in _do_copy_path
        self._copy_dir(srcpath)
      File "/root/sos-master/sos/plugins/__init__.py", line 449, in _copy_dir
        self._do_copy_path(os.path.join(srcpath, afile), dest=None)
      File "/root/sos-master/sos/plugins/__init__.py", line 522, in _do_copy_path
        self.archive.add_file(srcpath, dest)
      File "/root/sos-master/sos/archive.py", line 328, in add_file
        dest = self._check_path(dest, P_FILE)
      File "/root/sos-master/sos/archive.py", line 312, in _check_path
        raise ValueError(ve_msg % (dest, "regular file"))
    ValueError: path '/var/tmp/sos.R3QB3m/sosreport-pmoravec-sat65-htb-2019-03-19-relfvyz/var/log/httpd/foreman-ssl_access_ssl.log' exists and is not a regular file

The reason is:
- `apache` plugin collects the dir with *different* (smaller) logsize
- so some file is tailed and the logfile is a symlink to `sos_strings` subdir
- `satellite` plugin wants to collect whole file due to bigger logsize, so it calls `add_file`
- a symlink is detected where nothing or a regular file is expected

What plugin shall have preference? With smaller or bigger sizelimit? If with bigger, then a proper fix would be in this specific situation to:
- remove symlink target file
- remove symlink
- continue in `add_file`

If smaller sizelimit shall be applied, then we should just catch the exception, verify it is this specific case and pass?

Artificial reproducer: two almost identical plugins like:

    from sos.plugins import Plugin, RedHatPlugin, UbuntuPlugin, DebianPlugin
    
    
    class Mess1(Plugin, RedHatPlugin, UbuntuPlugin, DebianPlugin):
        """/var/log/messages* to collect"""
    
        plugin_name = "mess1"
    
        def setup(self):
            self.add_copy_spec("/var/log/messages*", 2)

Once with the sizelimit (smaller than `/var/log/messages`, once without the limit. (and call sos with --threads=1).

**Comment by pmoravec** [comment]
Btw having #1601 implemented, the chance to hit this error is much smaller - to hit it, there would have to be 2 plugins collecting the same file with different `log-size`. But `logsize` usually defaults to the same value.

**Comment by pmoravec** [comment]
Hm, I was wrong; with #1525 in place, `foreman` plugin raises the same exception on `foreman-ssl_access_ssl.log` - since `apache` plugin tails the usually big file while `foreman` plugin tries to collect it whole.
