### ISSUE TITLE
foreman plugin raises exception when scrubbing file with unicode chars

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1614]
# cat /var/tmp/sosreport-pmoravec-sat64-on-rhev-2019-03-22-lrqgygk/sos_logs/foreman-plugin-errors.txt 
    Traceback (most recent call last):
      File "/root/sos-master/sos/sosreport.py", line 1171, in postproc
        plug.postproc()
      File "/root/sos-master/sos/plugins/foreman.py", line 205, in postproc
        r"\1********")
      File "/root/sos-master/sos/plugins/__init__.py", line 380, in do_path_regex_sub
        self.do_file_sub(file['srcpath'], regexp, subst)
      File "/root/sos-master/sos/plugins/__init__.py", line 359, in do_file_sub
        if e.errno == errno.ENOENT:
    AttributeError: 'exceptions.UnicodeDecodeError' object has no attribute 'errno'

We need in https://github.com/sosreport/sos/blob/master/sos/plugins/__init__.py#L359 to properly catch exceptions that dont have `errno`.

**Comment by bmr-cymru** [comment]
That link's not a permalink, so it has shifted now that predicates have gone in :-)
