### ISSUE TITLE
Sosreport too weakly stops threads of timeouted plugins

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1736]
Reproducer: let sosreport collect too many files for some plugin (example: create rich dir.structure under `/var/lib/sesame` and run `sosreport -o qpid --plugin-timeout=10`). Then the following can happen:

- plugin times out
- the thread for the plugin still collects data and copies files under temp/working dir
- sosreport tries to create tarball that fails in `archive`'s `cleanup`
- as a result, whole temp. dir is removed _without_ keeping the tarball created - so the sosreport produces _nothing_

When using `--build` option, the above does not happen (while the plugin thread is stopped by hitting exception like https://github.com/sosreport/sos/issues/1641 - as it cant write files to just deleted temp.dir).

Few ideas how to fix this:
- few ways of catching the `archive.cleanup` exception exist - then we can get the build dir or even the tarball, BUT whole sosreport app can raise uncaught exception like below due to the timeouted plugin _still_ generating new content:

    Traceback (most recent call last):
      File "/usr/sbin/sosreport", line 19, in <module>
        main(sys.argv[1:])
      File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1384, in main
        sos.execute()
      File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1369, in execute
        self._cleanup()
      File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1322, in _cleanup
        self.archive.cleanup()
      File "/usr/lib/python2.7/site-packages/sos/archive.py", line 525, in cleanup
        shutil.rmtree(self._archive_root)
      File "/usr/lib64/python2.7/shutil.py", line 247, in rmtree
        rmtree(fullname, ignore_errors, onerror)
      File "/usr/lib64/python2.7/shutil.py", line 256, in rmtree
        onerror(os.rmdir, path, sys.exc_info())
      File "/usr/lib64/python2.7/shutil.py", line 254, in rmtree
        os.rmdir(path)
    OSError: [Errno 39] Directory not empty: '/var/tmp/sos.iyv0tN/sosreport-pmoravec-rhel76-2019-07-25-xhgfjej/etc'

- so I think the right fix should be rather forceful termination of plugins' threads before calling `archive.finalize()`

**Comment by pmoravec** [comment]
Idea of a fix: when main thread detects timeout, it orders the timeouted plugin to stop collecting further data, like:

1) `sosreport.py` in `_collect_plugin` when catching `TimeoutError:` will call plugin's new method to stop the plugin:

    self.loaded_plugins[plugin[0]-1][1].stop()

2) `plugin` API will have something like:

         def stop(self):
             self._stopped = True
     
         def collect(self):
             """Collect the data for a plugin."""
             self._stopped = False                          ##### newly added
             start = time()

3) in the beginning of `_do_copy_path` and `_get_cmd_output_now` and inside loop of `_collect_strings`, there will be test like:

            if self._stopped:
                return


Limitation: a command execution or big file copy happening during timeout will cause new file can still be added when archive tries to clean up the working dir. Maybe we can call `self.plugpool.shutdown(wait=True)` before calling `archive.finalize()` to prevent this latest race condition?
