### ISSUE TITLE
openstack_keystone collects /var/log/httpd that can be in conflict with apache plugin

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1950]
Under a smoke test on OSP keystone system, I got plugin exception:

    Traceback (most recent call last):
      File "/root/sos-master/sos/sosreport.py", line 1057, in collect_plugin
        plug.collect()
      File "/root/sos-master/sos/plugins/__init__.py", line 1518, in collect
        self._collect_copy_specs()
      File "/root/sos-master/sos/plugins/__init__.py", line 1487, in _collect_copy_specs
        self._do_copy_path(path)
      File "/root/sos-master/sos/plugins/__init__.py", line 872, in _do_copy_path
        self.archive.add_file(srcpath, dest)
      File "/root/sos-master/sos/archive.py", line 335, in add_file
        dest = self._check_path(dest, P_FILE)
      File "/root/sos-master/sos/archive.py", line 319, in _check_path
        raise ValueError(ve_msg % (dest, "regular file"))
    ValueError: path '/var/tmp/sos.vzQvb8/sosreport-osp11-1-2020-02-13-qehtpwt/var/log/httpd/keystone_wsgi_admin_access.log' exists and is not a regular file

That is due to:

    2020-02-13 18:29:26,788 INFO: [plugin:apache] collecting tail of '/var/log/httpd/keystone_wsgi_admin_access.log' due to size limit
    2020-02-13 18:29:27,003 INFO: [plugin:apache] skipping '/var/log/httpd/keystone_wsgi_main_access.log' over size limit
    ..
    2020-02-13 18:37:39,005 INFO: [plugin:apache] collecting string ...'127.0.0.1 - - [26/Jul/2017:08:40:17 +0530] "GET /v3/domains HTTP/1.1" 200 165 "-" "python-keystoneclient"' as 'var.log.httpd.keystone_wsgi_admin_access.log.tailed'
    ..
    2020-02-13 18:38:32,029 INFO: [plugin:openstack_keystone] collecting path '/var/log/httpd/keystone_wsgi_admin_access.log'
    2020-02-13 18:38:32,175 ERROR: caught exception in plugin method "openstack_keystone.collect()"

I can reproduce it when using `-a` option, only(?). Reproducer is either way a tricky, `apache` plugin must apply sizelimit and tailit exactly on the `keystone` logfiles.

Worth extending https://github.com/sosreport/sos/blob/master/sos/plugins/apache.py#L34 also by `/var/log/httpd/keystone*`?

Cc @TurboTurtle

**Comment by bmr-cymru** [comment]
Ugh. Yeah that's another problem of colliding size limits, coupled with the archive enforcing the file type match. I think moving it to apache is the best option without major changes.
