### ISSUE TITLE
Running sos [collect|report] from a deleted directory fails (more than before/needed)

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2332]
Reproducer:

    mkdir -p /var/tmp/aux
    cd /var/tmp/aux
    rm -rf /var/tmp/aux
    sos report -o host --batch --build

raises:

    Traceback (most recent call last):
      File "/usr/sbin/sos", line 14, in <module>
        sys.path.insert(0, os.getcwd())
    FileNotFoundError: [Errno 2] No such file or directory

`sos collect` behaves the same. Prior sos-4.0, we run the tool, "just" hit some errors (not sure if/what impact):

    # cat /var/tmp/sosreport-pmoravec-rhel8-2020-12-09-zsmgakj/sos_logs/host-plugin-errors.txt
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/sos/sosreport.py", line 1114, in collect_plugin
        plug.collect()
      File "/usr/lib/python3.6/site-packages/sos/plugins/__init__.py", line 955, in collect
        self._collect_cmd_output()
      File "/usr/lib/python3.6/site-packages/sos/plugins/__init__.py", line 931, in _collect_cmd_output
        sizelimit=sizelimit)
      File "/usr/lib/python3.6/site-packages/sos/plugins/__init__.py", line 764, in get_cmd_output_now
        self.archive.add_link(outfn, root_symlink)
      File "/usr/lib/python3.6/site-packages/sos/archive.py", line 422, in add_link
        host_path_name = os.path.realpath(os.path.join(source_dir, source))
      File "/usr/lib64/python3.6/posixpath.py", line 396, in realpath
        return abspath(path)
      File "/usr/lib64/python3.6/posixpath.py", line 383, in abspath
        cwd = os.getcwd()
    FileNotFoundError: [Errno 2] No such file or directory
    #

But the `host` plugin collects *some* data (not all, and other plugins collect less).

It is trivial to add a catch block around the `sys.path.insert` (on 3 places) to restore the pre-4.0 behaviour. My questions are: is it safe (python always raised that exception when running `os.path.realpath` in a deleted directory)? Should we run `sos` and skip collecting some data due to the uncaught exception from python library (or shall we catch that exception as well?)? Or, from the opposite side, isn't it usefull to tell a user by the current "no-op exception" that they are in a nonexisting directory?

**Comment by pmoravec** [comment]
The https://github.com/sosreport/sos/pull/2331 wrongly refers to this Issue - it should refer to itself.

After some IRC discussion, nobody wanted to revert back the behaviour "let run sos from deleted directory and let it skip collecting some data". So the current behaviour is taken as the desired one.

Closing the issue therefore.
