### ISSUE TITLE
OpenShift 4 - sos collect fails because podman cannot pull support-tools container due to missing credentials

### ISSUE THREAD

**Issue by andreaskaris** [sosreport/sos#2534]
Hi,

sos collect fails because podman cannot pull support-tools container due to missing credentials

The error message is 
~~~
[openshift-worker-1:create_sos_container] Could not start container after create: 
Error: no container with name or ID sos-collector-tmp found: no such container
~~~

Full log:
~~~
[root@openshift-jumpserver-0 sos]# bin/sos collect --case-id 00009999 --no-local --nopasswd-sudo --ssh-user core -i ~/.ssh/gss-stack-tools  --nodes=openshift-worker-1.example.com,openshift-worker-0.example.com,openshift-master-0.example.com,openshift-master-1.example.com,openshift-master-2.example.com
WARNING: Unable to read configuration file /etc/sos/sos.conf : No such file or directory

sos-collector (version 4.1)

This utility is used to collect sosreports from multiple nodes simultaneously.
It uses OpenSSH's ControlPersist feature to connect to nodes and run commands
remotely. If your system installation of OpenSSH is older than 5.6, please
upgrade.

An archive of sosreport tarballs collected from the nodes will be generated in
/var/tmp/sos.3jcuy0mf and may be provided to an appropriate support
representative.

The generated archive may contain data considered sensitive and its content
should be reviewed by the originating organization before being passed to any
third party.

No configuration changes will be made to the system running this utility or
remote systems that it connects to.


Press ENTER to continue, or CTRL-C to quit


sos-collector ASSUMES that SSH keys are installed on all nodes unless the
--password option is provided.



The following is a list of nodes to collect from:
	openshift-master-0.example.com
	openshift-master-1.example.com
	openshift-master-2.example.com
	openshift-worker-0.example.com
	openshift-worker-1.example.com


Press ENTER to continue with these nodes, or press CTRL-C to quit



Connecting to nodes...
[openshift-worker-1:create_sos_container] Could not start container after create: 
Error: no container with name or ID sos-collector-tmp found: no such container

[openshift-master-1:create_sos_container] Could not start container after create: 
Error: no container with name or ID sos-collector-tmp found: no such container

[openshift-master-0:create_sos_container] Could not start container after create: 
Error: no container with name or ID sos-collector-tmp found: no such container

[openshift-master-2:create_sos_container] Could not start container after create: 
Error: no container with name or ID sos-collector-tmp found: no such container


Beginning collection of sosreports from 1 nodes, collecting a maximum of 4 concurrently

openshift-worker-0              : Generating sosreport...
^CExiting on user cancel

[root@openshift-jumpserver-0 sos]# 
~~~

This happens because sos collect uses podman and not crio - and podman is not registered in OCP 4 by default as opposed to crio:
~~~
[root@openshift-worker-1 ~]# podman pull registry.redhat.io/rhel8/support-tools
Trying to pull registry.redhat.io/rhel8/support-tools:latest...
  unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
Error: Error initializing source docker://registry.redhat.io/rhel8/support-tools:latest: unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication

[root@openshift-worker-1 ~]# crictl pull registry.redhat.io/rhel8/support-tools
Image is up to date for registry.redhat.io/rhel8/support-tools@sha256:6d88895cd0594dbc891fafd63e23055fb5b81a8d5cc6b98901bd8d29d230941b
~~~

In order to pull the image, we must specify the authfile:
~~~
[root@openshift-worker-1 ~]# podman pull --authfile /var/lib/kubelet/config.json registry.redhat.io/rhel8/support-tools
Trying to pull registry.redhat.io/rhel8/support-tools:latest...
Getting image source signatures
Copying blob f4d7bf6cac1a skipped: already exists  
Copying blob 55eda7743468 skipped: already exists  
Copying blob 4b21dcdd136d [--------------------------------------] 0.0b / 0.0b
Copying config bd3dd127d7 done  
Writing manifest to image destination
Storing signatures
bd3dd127d7f95ce2c12fb253bd3fbd87e146384db363dc0a2f285cc66e47b7db
~~~

I did this manually on all nodes and ran `sos collect` again:
~~~
for n in openshift-master-0.example.com openshift-master-1.example.com openshift-master-2.example.com openshift-worker-0.example.com openshift-worker-1.example.com; do ssh core@$n sudo podman pull --authfile /var/lib/kubelet/config.json registry.redhat.io/rhel8/support-tools ; done
~~~

And then, this works:
~~~
[root@openshift-jumpserver-0 sos]# bin/sos collect --case-id 00009999 --jobs 1 --no-local --nopasswd-sudo --ssh-user core -i ~/.ssh/gss-stack-tools --master=openshift-master-0.example.com --nodes=openshift-worker-1.example.com,openshift-worker-0.example.com,openshift-master-0.example.com,openshift-master-1.example.com,openshift-master-2.example.com
WARNING: Unable to read configuration file /etc/sos/sos.conf : No such file or directory

sos-collector (version 4.1)

This utility is used to collect sosreports from multiple nodes simultaneously.
It uses OpenSSH's ControlPersist feature to connect to nodes and run commands
remotely. If your system installation of OpenSSH is older than 5.6, please
upgrade.

An archive of sosreport tarballs collected from the nodes will be generated in
/var/tmp/sos.c_m6gh5s and may be provided to an appropriate support
representative.

The generated archive may contain data considered sensitive and its content
should be reviewed by the originating organization before being passed to any
third party.

No configuration changes will be made to the system running this utility or
remote systems that it connects to.


Press ENTER to continue, or CTRL-C to quit


sos-collector ASSUMES that SSH keys are installed on all nodes unless the
--password option is provided.



Connected to openshift-master-0.example.com, determining cluster type...

The following is a list of nodes to collect from:
	openshift-master-0            
	openshift-master-1.example.com
	openshift-master-2.example.com
	openshift-worker-0.example.com
	openshift-worker-1.example.com


Press ENTER to continue with these nodes, or press CTRL-C to quit


Connecting to nodes...

Beginning collection of sosreports from 5 nodes, collecting a maximum of 1 concurrently

openshift-master-0              : Generating sosreport...
(...)
~~~

**Comment by TurboTurtle** [comment]
This should be resolved by #2544 if you're able to test that, it'd be appreciated. There is not jump host support yet, so you'd still need to either run `sos collect` from a node with `oc` configured such that it can enumerate the cluster nodes, or point it at a node that can with `--master=<address>`.  The other changes include adding options and controls for registry auth, as mentioned here. For RHCOS, it will default to using `/var/lib/kubelet/config.json` as an authfile if it exists.

**Comment by andreaskaris** [comment]
Sorry, I missed this here.

With upstream:
~~~
[root@openshift-jumpserver-0 ~]# cd sos
[root@openshift-jumpserver-0 sos]# sos collect --case-id 00009999 --no-local --nopasswd-sudo --ssh-user core -i ~/.ssh/gss-stack-tools --master=openshift-master-0.example.com --nodes=openshift-worker-1.example.com,openshift-worker-0.example.com,openshift-master-0.example.com,openshift-master-1.example.com,openshift-master-2.example.com
-bash: /usr/sbin/sos: No such file or directory
[root@openshift-jumpserver-0 sos]# bin/sos collect --case-id 00009999 --no-local --nopasswd-sudo --ssh-user core -i ~/.ssh/gss-stack-tools --master=openshift-master-0.example.com --nodes=openshift-worker-1.example.com,openshift-worker-0.example.com,openshift-master-0.example.com,openshift-master-1.example.com,openshift-master-2.example.com
WARNING: Unable to read configuration file /etc/sos/sos.conf : No such file or directory

sos-collector (version 4.1)

This utility is used to collect sosreports from multiple nodes simultaneously.
It uses OpenSSH's ControlPersist feature to connect to nodes and run commands
remotely. If your system installation of OpenSSH is older than 5.6, please
upgrade.

An archive of sosreport tarballs collected from the nodes will be generated in
/var/tmp/sos.3x3kbzxm and may be provided to an appropriate support
representative.

The generated archive may contain data considered sensitive and its content
should be reviewed by the originating organization before being passed to any
third party.

No configuration changes will be made to the system running this utility or
remote systems that it connects to.


Press ENTER to continue, or CTRL-C to quit


sos-collector ASSUMES that SSH keys are installed on all nodes unless the
--password option is provided.


[openshift-master-0:create_sos_container] Could not start container after create: 
Error: no container with name or ID sos-collector-tmp found: no such container

Could not connect to master node. Aborting...
~~~

With this fix:
~~~
[root@openshift-jumpserver-0 ~]# git clone https://github.com/TurboTurtle/sos.git
Cloning into 'sos'...
remote: Enumerating objects: 30838, done.
remote: Counting objects: 100% (1159/1159), done.
remote: Compressing objects: 100% (534/534), done.
remote: Total 30838 (delta 723), reused 910 (delta 603), pack-reused 29679
Receiving objects: 100% (30838/30838), 8.69 MiB | 19.64 MiB/s, done.
Resolving deltas: 100% (22601/22601), done.
[root@openshift-jumpserver-0 ~]# git branch -r
fatal: not a git repository (or any of the parent directories): .git
[root@openshift-jumpserver-0 ~]# cd sos/
[root@openshift-jumpserver-0 sos]# git checkout origin/ocp4-collect-improvements
Note: switching to 'origin/ocp4-collect-improvements'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 48a35ab8 [ocp] Add cluster profile for OCP4
[root@openshift-jumpserver-0 sos]#  
[root@openshift-jumpserver-0 sos]# bin/sos collect --case-id 00009999 --no-local --nopasswd-sudo --ssh-user core -i ~/.ssh/gss-stack-tools --master=openshift-master-0.example.com --nodes=openshift-worker-1.example.com,openshift-worker-0.example.com,openshift-master-0.example.com,openshift-master-1.example.com,openshift-master-2.example.com
WARNING: Unable to read configuration file /etc/sos/sos.conf : No such file or directory

sos-collector (version 4.1)

This utility is used to collect sosreports from multiple nodes simultaneously.
It uses OpenSSH's ControlPersist feature to connect to nodes and run commands
remotely. If your system installation of OpenSSH is older than 5.6, please
upgrade.

An archive of sosreport tarballs collected from the nodes will be generated in
/var/tmp/sos.980qpuox and may be provided to an appropriate support
representative.

The generated archive may contain data considered sensitive and its content
should be reviewed by the originating organization before being passed to any
third party.

No configuration changes will be made to the system running this utility or
remote systems that it connects to.


Press ENTER to continue, or CTRL-C to quit


sos-collector ASSUMES that SSH keys are installed on all nodes unless the
--password option is provided.


Connected to openshift-master-0.example.com, determining cluster type...
Cluster type set to OpenShift Container Platform v4
Cluster failed to enumerate nodes: 'oc' failed due to missing kubeconfig on master node. Specify one via '-c ocp.kubeconfig=<path>'

The following is a list of nodes to collect from:
	openshift-master-0            
	openshift-master-1.example.com
	openshift-master-2.example.com
	openshift-worker-0.example.com
	openshift-worker-1.example.com


Press ENTER to continue with these nodes, or press CTRL-C to quit



Connecting to nodes...
[openshift-worker-0.example.com:__init__] Unable to open SSH session: Host requested password, but none provided
(...)
~~~

**Comment by TurboTurtle** [comment]
> Cluster failed to enumerate nodes: 'oc' failed due to missing kubeconfig on master node. Specify one via '-c ocp.kubeconfig=<path>'

Whatever you point `--master` at (or if you run it locally without that option) needs a functional `oc` (or available kubeconfig) to enumerate nodes. This does _not_ need to actually be a node in the cluster. If your lab (is it quicklab?) has a bastion host, try running it there (or with `--master=$bastion`) and dropping the `--nodes` option to see if the enumeration works correctly.

**Comment by andreaskaris** [comment]
I suppose that this *would* work if my node names FQDNs actually matched my  FQDNs:
~~~
[root@openshift-jumpserver-0 sos]# bin/sos collect --case-id 00009999 --no-local --nopasswd-sudo --ssh-user core -i ~/.ssh/gss-stack-tools --cluster-type openshift
WARNING: Unable to read configuration file /etc/sos/sos.conf : No such file or directory

sos-collector (version 4.1)

This utility is used to collect sosreports from multiple nodes simultaneously.
It uses OpenSSH's ControlPersist feature to connect to nodes and run commands
remotely. If your system installation of OpenSSH is older than 5.6, please
upgrade.

An archive of sosreport tarballs collected from the nodes will be generated in
/var/tmp/sos.yk952cdo and may be provided to an appropriate support
representative.

The generated archive may contain data considered sensitive and its content
should be reviewed by the originating organization before being passed to any
third party.

No configuration changes will be made to the system running this utility or
remote systems that it connects to.


Press ENTER to continue, or CTRL-C to quit


sos-collector ASSUMES that SSH keys are installed on all nodes unless the
--password option is provided.



The following is a list of nodes to collect from:
	openshift-master-0
	openshift-master-1
	openshift-master-2
	openshift-worker-0
	openshift-worker-1


Press ENTER to continue with these nodes, or press CTRL-C to quit



Connecting to nodes...
[openshift-master-2:__init__] Unable to open SSH session: Could not connect to host openshift-master-2 on specified port 
[openshift-master-1:__init__] Unable to open SSH session: Could not connect to host openshift-master-1 on specified port 
[openshift-master-0:__init__] Unable to open SSH session: Could not connect to host openshift-master-0 on specified port 
[openshift-worker-1:__init__] Unable to open SSH session: Could not connect to host openshift-worker-1 on specified port 
[openshift-worker-0:__init__] Unable to open SSH session: Could not connect to host openshift-worker-0 on specified port 
No nodes connected. Aborting...
~~~

By the way - when a wrong key value is provided, it would be nice to catch this and to provide a list of valid plugins:
~~~
[root@openshift-jumpserver-0 sos]# bin/sos collect --case-id 00009999 --no-local --nopasswd-sudo --ssh-user core -i ~/.ssh/gss-stack-tools --cluster-type ocp
WARNING: Unable to read configuration file /etc/sos/sos.conf : No such file or directory

sos-collector (version 4.1)

This utility is used to collect sosreports from multiple nodes simultaneously.
It uses OpenSSH's ControlPersist feature to connect to nodes and run commands
remotely. If your system installation of OpenSSH is older than 5.6, please
upgrade.

An archive of sosreport tarballs collected from the nodes will be generated in
/var/tmp/sos.7ra2te90 and may be provided to an appropriate support
representative.

The generated archive may contain data considered sensitive and its content
should be reviewed by the originating organization before being passed to any
third party.

No configuration changes will be made to the system running this utility or
remote systems that it connects to.


Press ENTER to continue, or CTRL-C to quit


sos-collector ASSUMES that SSH keys are installed on all nodes unless the
--password option is provided.


Traceback (most recent call last):
  File "bin/sos", line 22, in <module>
    sos.execute()
  File "/root/sos/sos/__init__.py", line 186, in execute
    self._component.execute()
  File "/root/sos/sos/collector/__init__.py", line 1084, in execute
    self.prep()
  File "/root/sos/sos/collector/__init__.py", line 782, in prep
    self.cluster = self.clusters[self.opts.cluster_type]
KeyError: 'ocp'
~~~

**Comment by TurboTurtle** [comment]
> KeyError: 'ocp'

Silly question - but are you sure you're on the branch for #2544 ? The old profile was named 'openshift', the new one is exclusively 'ocp'.

Either way, yeah we can handle that error better.

**Comment by andreaskaris** [comment]
No, I wasn't :-/

Here we go:
~~~
[root@openshift-jumpserver-0 sos]#  bin/sos collect --case-id 00009999 --no-local --nopasswd-sudo --ssh-user core -i ~/.ssh/gss-stack-tools --cluster-type ocp

sos-collector (version 4.1)

This utility is used to collect sosreports from multiple nodes simultaneously.
It uses OpenSSH's ControlPersist feature to connect to nodes and run commands
remotely. If your system installation of OpenSSH is older than 5.6, please
upgrade.

An archive of sosreport tarballs collected from the nodes will be generated in
/var/tmp/sos.yyk9hrq5 and may be provided to an appropriate support
representative.

The generated archive may contain data considered sensitive and its content
should be reviewed by the originating organization before being passed to any
third party.

No configuration changes will be made to the system running this utility or
remote systems that it connects to.


Press ENTER to continue, or CTRL-C to quit


sos-collector ASSUMES that SSH keys are installed on all nodes unless the
--password option is provided.



The following is a list of nodes to collect from:
	openshift-master-0
	openshift-master-1
	openshift-master-2
	openshift-worker-1
	openshift-worker-2


Press ENTER to continue with these nodes, or press CTRL-C to quit



Connecting to nodes...
[openshift-master-1:__init__] Unable to open SSH session: Could not connect to host openshift-master-1 on specified port 
[openshift-worker-1:__init__] Unable to open SSH session: Could not connect to host openshift-worker-1 on specified port 
[openshift-master-0:__init__] Unable to open SSH session: Could not connect to host openshift-master-0 on specified port 
[openshift-worker-2:__init__] Unable to open SSH session: Could not connect to host openshift-worker-2 on specified port 
[openshift-master-2:__init__] Unable to open SSH session: Could not connect to host openshift-master-2 on specified port 
No nodes connected. Aborting...
~~~

With a modified `search` domain in resolv.conf:
~~~
[root@openshift-jumpserver-0 sos]#  bin/sos collect --case-id 00009999 --no-local --nopasswd-sudo --ssh-user core -i ~/.ssh/gss-stack-tools --cluster-type ocp

sos-collector (version 4.1)

This utility is used to collect sosreports from multiple nodes simultaneously.
It uses OpenSSH's ControlPersist feature to connect to nodes and run commands
remotely. If your system installation of OpenSSH is older than 5.6, please
upgrade.

An archive of sosreport tarballs collected from the nodes will be generated in
/var/tmp/sos.a6pfa054 and may be provided to an appropriate support
representative.

The generated archive may contain data considered sensitive and its content
should be reviewed by the originating organization before being passed to any
third party.

No configuration changes will be made to the system running this utility or
remote systems that it connects to.


Press ENTER to continue, or CTRL-C to quit
 

sos-collector ASSUMES that SSH keys are installed on all nodes unless the
--password option is provided.



The following is a list of nodes to collect from:
	openshift-master-0
	openshift-master-1
	openshift-master-2
	openshift-worker-1
	openshift-worker-2


Press ENTER to continue with these nodes, or press CTRL-C to quit



Connecting to nodes...

Beginning collection of sosreports from 5 nodes, collecting a maximum of 4 concurrently

openshift-master-1  : Generating sosreport...
openshift-master-2  : Generating sosreport...
openshift-worker-1  : Generating sosreport...
openshift-master-0  : Generating sosreport...
openshift-worker-1  : Retrieving sosreport...
openshift-worker-1  : Successfully collected sosreport
openshift-worker-2  : Generating sosreport...

(...)
~~~

**Comment by TurboTurtle** [comment]
Excellent!

I'll get this merged and I'll follow it up with better handling for an incorrect cluster name.
