### ISSUE TITLE
[4.2] avocado framework not available in Ubuntu

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2653]
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_sosreport/build/tests/sos_tests.py", line 10, in <module>
    from avocado.core.exceptions import TestSkipError
ModuleNotFoundError: No module named 'avocado' 
```

Would it be a good idea to bundle the framework into sosreport ? or else ?

**Comment by TurboTurtle** [comment]
Our testing, across all distros, is done by installing avocado via PyPi - https://github.com/sosreport/sos/blob/main/.cirrus.yml#L127 - and producing source tarballs via distutils does not include the test suite on purpose.

I'm not sure I follow why the test suite would be desired to be packaged alongside any given downstream's release?

**Comment by slashdd** [comment]
@TurboTurtle I'll troubleshoot more in the following days.

**Comment by slashdd** [comment]
[build log](https://launchpadlibrarian.net/554193650/buildlog_ubuntu-impish-amd64.sosreport_4.2-1ubuntu1_BUILDING.txt.gz)

```
Failure: ModuleNotFoundError (No module named 'sos_tests') ... ERROR
Failure: ModuleNotFoundError (No module named 'avocado') ... ERROR
Failure: ModuleNotFoundError (No module named 'sos_tests') ... ERROR
Failure: ModuleNotFoundError (No module named 'sos_tests') ... ERROR
Failure: ModuleNotFoundError (No module named 'sos_tests') ... ERROR
Failure: ModuleNotFoundError (No module named 'avocado') ... ERROR
Failure: ModuleNotFoundError (No module named 'sos_tests') ... ERROR
Failure: ModuleNotFoundError (No module named 'sos_tests') ... ERROR
Failure: ModuleNotFoundError (No module named 'avocado') ... ERROR
Failure: ModuleNotFoundError (No module named 'sos_tests') ... ERROR
Failure: ModuleNotFoundError (No module named 'avocado') ... ERROR

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'sos_tests')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_sosreport/build/tests/cleaner_tests/help_output_tests.py", line 10, in <module>
    from sos_tests import StageOneOutputTest
ModuleNotFoundError: No module named 'sos_tests'

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'avocado')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_sosreport/build/tests/collect_tests/help_output_tests.py", line 13, in <module>
    from avocado.utils import software_manager
ModuleNotFoundError: No module named 'avocado'
```

**Comment by TurboTurtle** [comment]
I'm not familiar with packaging guidelines for .debs, but I still don't understand the desire to package the test suite.

Beyond that, the `ModuleNotFoundError: No module named 'sos_tests'` error is because you need to specify the path, like we do for our CI testing - https://github.com/sosreport/sos/blob/main/.cirrus.yml#L126.

**Comment by slashdd** [comment]
@TurboTurtle I'll look this out. Thanks

**Comment by slashdd** [comment]
@TurboTurtle what version of avocado-framework version is used for the testing ? 
I'm having error with avocado 90.0 and wondering before I continue the troubleshoot if I use the right version.

**Comment by slashdd** [comment]
https://launchpadlibrarian.net/557269937/buildlog_ubuntu-impish-amd64.sosreport_4.2-1ubuntu2.11_BUILDING.txt.gz

```
======================================================================
ERROR: 0-CleanHelpTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_sosreport/build/tests/sos_tests.py", line 230, in setUp
    if not os.path.isdir(self.tmpdir):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_sosreport/build/tests/sos_tests.py", line 81, in tmpdir
    self._tmpdir = os.getenv('AVOCADO_TESTS_COMMON_TMPDIR') + self.klass_name
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
-------------------- >> begin captured logging << --------------------
avocado.test: INFO: INIT 0-CleanHelpTest
avocado.test: DEBUG: PARAMS (key=timeout, path=*, default=None) => None
avocado.test: DEBUG: Test metadata:
avocado.test: DEBUG:   filename: /<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_sosreport/build/tests/cleaner_tests/help_output_tests.py
avocado.test: DEBUG:   workdir: /tmp/avocado_test_wfg8z0hn/test-results/tmp_dirww8j7rey/0-CleanHelpTest
avocado.test: INFO: INIT 0-MaskHelpTest
avocado.test: DEBUG: PARAMS (key=timeout, path=*, default=None) => None
avocado.test: DEBUG: Test metadata:
avocado.test: DEBUG:   filename: /<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_sosreport/build/tests/cleaner_tests/help_output_tests.py
avocado.test: DEBUG:   workdir: /tmp/avocado_test_n_doji0s/test-results/tmp_dirx278hjga/0-MaskHelpTest
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: 0-MaskHelpTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_sosreport/build/tests/sos_tests.py", line 230, in setUp
    if not os.path.isdir(self.tmpdir):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_sosreport/build/tests/sos_tests.py", line 81, in tmpdir
    self._tmpdir = os.getenv('AVOCADO_TESTS_COMMON_TMPDIR') + self.klass_name
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by slashdd** [comment]
Look like 'AVOCADO_TESTS_COMMON_TMPDIR' represent nothing, and nothing is assigned to this variable by default.

**Comment by slashdd** [comment]
```
>>> import os
>>> test = os.getenv('AVOCADO_TESTS_COMMON_TMPDIR') + 'potato'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
>>> test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'test' is not defined
```

**Comment by slashdd** [comment]
https://github.com/avocado-framework/avocado/blob/master/docs/source/guides/writer/chapters/writing.rst

```
AVOCADO_TESTS_COMMON_TMPDIR | Temporary directory created by the teststmpdir plugin. The directory is persistent throughout the tests in the same Job
-- | --



```

**Comment by slashdd** [comment]
I could possibly force it in d/rules by adding something like this:
`export AVOCADO_TESTS_COMMON_TMPDIR=/tmp`

I'll give it a try.

**Comment by slashdd** [comment]
It did the work, but here's another blocker. I wonder why you don't have such problem in your Ubuntu testing.

Still investigating why 'output' is not created under the directory

```
ls -altr /tmp/sos_tests.py.StageOneReportTest/
total 20
-rw-r--r--  1 root root  1273 Sep  7 17:46 pre_sysinfo
drwxr-xr-x  2 root root  4096 Sep  7 17:46 .
drwxrwxrwt 34 root root 12288 Sep  7 17:46 ..

```
```
======================================================================
ERROR: Ensure that no additional kernel modules have been loaded during an
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/impish/sos-4.2/.pybuild/cpython3_3.9_sosreport/build/tests/sos_tests.py", line 410, in setUp
    super(BaseSoSReportTest, self).setUp()
  File "/tmp/impish/sos-4.2/.pybuild/cpython3_3.9_sosreport/build/tests/sos_tests.py", line 247, in setUp
    with open(os.path.join(self.tmpdir, 'output'), 'rb') as pfile:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/sos_tests.py.StageOneReportTest/output'
```
