### ISSUE TITLE
[4.2] avocado testsuite on Ubuntu

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2683]
Either with avocado-framework (90.0) (debianized) or simple pip3 install avocado-framework (91.0), I get the following error for all tests un Ubuntu:

Same result using PPA or local fakeroot (w/ python 3.8 and 3.9)
Reproducible everytime (tested in Focal/20.04LTS and Impish (Active devel release)

```
======================================================================
ERROR: 0-CleanHelpTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/sos/sos-4.2/.pybuild/cpython3_3.9_sosreport/build/tests/sos_tests.py", line 244, in setUp
    self._execute_sos_cmd()
  File "/var/tmp/sos/sos-4.2/.pybuild/cpython3_3.9_sosreport/build/tests/sos_tests.py", line 123, in _execute_sos_cmd
    self.cmd_output = process.run(exec_cmd, timeout=self.sos_timeout)
  File "/usr/local/lib/python3.9/dist-packages/avocado/utils/process.py", line 1079, in run
    cmd_result = sp.run(timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/avocado/utils/process.py", line 952, in run
    self._init_subprocess()
  File "/usr/local/lib/python3.9/dist-packages/avocado/utils/process.py", line 666, in _init_subprocess
    raise details
  File "/usr/local/lib/python3.9/dist-packages/avocado/utils/process.py", line 659, in _init_subprocess
    self._popen = subprocess.Popen(cmd,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory (/var/tmp/sos/sos-4.2/.pybuild/cpython3_3.9_sosreport/build/bin/sos clean --help): '/var/tmp/sos/sos-4.2/.pybuild/cpython3_3.9_sosreport/build/bin
...
======================================================================
ERROR: 0-StageOneReportTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/sos/sos-4.2/.pybuild/cpython3_3.8_sosreport/build/tests/sos_tests.py", line 410, in setUp
    super(BaseSoSReportTest, self).setUp()
  File "/var/tmp/sos/sos-4.2/.pybuild/cpython3_3.8_sosreport/build/tests/sos_tests.py", line 247, in setUp
    with open(os.path.join(self.tmpdir, 'output'), 'rb') as pfile:
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/sos_tests.py.StageOneReportTest/output'
```

**Comment by TurboTurtle** [comment]
Sounds like #2666 - are you using `--test-runner=runner`?

**Comment by slashdd** [comment]
I did, unfortunately same error

**Comment by TurboTurtle** [comment]
I'll spin up a test VM to look into this early next week. The odd thing is our test suite runs on 20.04 without complaint.

What does the environment look like when you get these errors? What are the setup steps?

**Comment by slashdd** [comment]
The full buildlog can be found here: https://launchpadlibrarian.net/557777253/buildlog_ubuntu-impish-amd64.sosreport_4.2-1ubuntu2.21_BUILDING.txt.gz

```
Build-Depends:
 debhelper-compat (= 13),
 avocado,
 dh-python,
 gettext,
 kmod,
 python3-all,
 python3-nose,
 python3-setuptools,
 python3-sphinx,
```
And I have an autopkgtest restriction to run on a real machine, because sosreport interact may interact with kernel through the kernel plugin.

That's about it.

```
isolation-machine
The test wants to interact with the kernel, reboot the machine, or other things which fail in a simple schroot and even a container. 
```

**Comment by TurboTurtle** [comment]
It looks like the whole test suite is actually getting kicked off here:

`pybuild base:232: cd /<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_sosreport/build; python3.9 -m nose -v tests`

Meaning the avocado tests are being run by `nose`, which doesn't work.

For the nose tests, it'd need to be `nose -v tests/unittests/`.

I don't see anything actually directly invoking avocado, which would need to be done like this:

`avocado run --test-runner=runner -t stageone tests/{cleaner,collect,report,vendor}_tests`

**Comment by slashdd** [comment]
I had to reformat as follows for debian/rules:

```
 override_dh_auto_test:
	avocado run --test-runner=runner -t stageone tests/cleaner_tests
 	avocado run --test-runner=runner -t stageone tests/collect_tests
 	avocado run --test-runner=runner -t stageone tests/report_tests
 	avocado run --test-runner=runner -t stageone tests/vendor_tests
```
It works if I run the build locally using fakeroot.
Falling when sending to a PPA. 

I debug what could differ in a PPA.
I think I have enough to continue.

Thanks !
