### ISSUE TITLE
[foreman] scl_enable_tfm_gem_list does not work

### ISSUE THREAD

**Issue by matt8754** [sosreport/sos#2730]
I've observed following traceback in recent sosreports:

cat scl_enable_tfm_gem_list
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': /opt/rh/rh-ruby25/root/usr/share/gems/gems/psych-3.0.2/lib/psych/scalar_scanner.rb:146: syntax error, unexpected tIDENTIFIER, expecting ')' (SyntaxError)
      klass.new(yy, m, dd, hh, mm, ss+us/(1_000_000r), offset)
                                                    ^
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rh/rh-ruby25/root/usr/share/gems/gems/psych-3.0.2/lib/psych/nodes/node.rb:4:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rh/rh-ruby25/root/usr/share/gems/gems/psych-3.0.2/lib/psych/nodes.rb:2:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rh/rh-ruby25/root/usr/share/gems/gems/psych-3.0.2/lib/psych.rb:14:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'

**Comment by matt8754** [comment]
This also happens on old satellite version 6.7.5, so it seems like it's been like that for a while.

**Comment by pmoravec** [comment]
OK, there are two issues:

1) In upstream (not in the older sos versions), https://github.com/sosreport/sos/blob/main/sos/report/plugins/__init__.py#L2721-L2722 detects just very first SCL when generating `_scls_matched`, which results in https://github.com/sosreport/sos/blob/main/sos/report/plugins/__init__.py#L3031-L3032 skipping to collect the command at all.

2) We inject scl sub-path into `PATH` in https://github.com/sosreport/sos/blob/main/sos/report/plugins/__init__.py#L3019-L3024 (that was an advice we got during initial implementation of the `scl` stuff into sosreport). Now I learned that `scl` command itself does the same, hence the `PATH=....` is redundant. And in `tfm` case even harmfull, as even:

`scl enable tfm "PATH=/opt/theforeman/tfm/usr/local/sbin:/opt/theforeman/tfm/usr/local/bin:/opt/theforeman/tfm/root/bin:/opt/theforeman/tfm/usr/bin:/opt/theforeman/tfm/usr/sbin:/usr/sbin:/usr/bin:/root/bin:/usr/local/bin:/usr/local/sbin gem list"`

or:

`scl enable tfm 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin:/root/bin gem list'`

raises the same exception. While simple calling:

`scl enable tfm 'gem list'`

works fine.

**Comment by matt8754** [comment]
pmoravec++ thanks for the prompt response.  In a few cases, collecting gem list is quite useful as some customers could have messed up the gems. And I was actually confused with that scl PATH overwrite too, :-D
