### ISSUE TITLE
Sos collect errors for OCP cluster

### ISSUE THREAD

**Issue by npinaeva** [sosreport/sos#2777]
I tried to run the latest sos collect for OCP cluster from my local machine using
`bin/sos collect --no-local --batch -vvv --cluster-type ocp` command. I found a couple of errors and even fixed on my way:

1. Cleanup problem: when sos collect fails e.g. with `No nodes connected. Aborting...`, cluster cleanup isn't called and the next run you get this error:
```
[ux331un:run_command] Running command oc new-project sos-collect-tmp
[ocp] Failed to create project: Error from server (AlreadyExists): project.project.openshift.io "sos-collect-tmp" already exists

Traceback (most recent call last):
  File "bin/sos", line 22, in <module>
    sos.execute()
  File "/home/nadia/ocp/sos/sos/__init__.py", line 186, in execute
    self._component.execute()
  File "/home/nadia/ocp/sos/sos/collector/__init__.py", line 1100, in execute
    self.prep()
  File "/home/nadia/ocp/sos/sos/collector/__init__.py", line 812, in prep
    self.cluster.setup()
  File "/home/nadia/ocp/sos/sos/collector/clusters/ocp.py", line 83, in setup
    raise Exception("Failed to create temporary project for collection. "
Exception: Failed to create temporary project for collection. 
Aborting...
```
I solved this by adding `self.cluster.cleanup()` here https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L444 , but in general, sos collect doesn't seem to have a reliable way to cleanup, at least because there are multiple different exit points in the same function calling different shutdown functions, e.g. https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L1140 and https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L1164-L1166.

2. Nodes are listed wrong for ocp
Tried to fix that: https://github.com/sosreport/sos/pull/2776

3. `The command was not found or was not executable: oc`
`oc` is executable in the beginning but then sometimes it's getting lost. 
- during connecting to nodes `[ip-10-0-213-88.eu-central-1.compute.internal:read_file] Exception while reading /etc/os-release: The command was not found or was not executable: oc`
- during cleanup: 
```
No nodes connected. Aborting...
[ux331un:run_command] Running command oc delete project sos-collect-tmp
EXC: The command was not found or was not executable: oc.
```

I suspect it's because of newly created policies for cluster nodes, that do this: https://github.com/sosreport/sos/blob/main/sos/policies/__init__.py#L337 and mess up my local `PATH`

Also, amount of nodes that are connected very unstable, I get outputs like this 
0 nodes
```
Connecting to nodes...
[ip-10-0-213-88.eu-central-1.compute.internal:_connect] Starting sos collector container 'ip-10-0-213-88-sos-collector'
[ip-10-0-148-212.eu-central-1.compute.internal:_connect] Starting sos collector container 'ip-10-0-148-212-sos-collector'
[ip-10-0-188-118.eu-central-1.compute.internal:_connect] Starting sos collector container 'ip-10-0-188-118-sos-collector'
[ip-10-0-148-212.eu-central-1.compute.internal:_connect] Pod 'ip-10-0-148-212-sos-collector' successfully deployed, waiting for pod to enter ready state
[ip-10-0-213-88.eu-central-1.compute.internal:_connect] Pod 'ip-10-0-213-88-sos-collector' successfully deployed, waiting for pod to enter ready state
[ip-10-0-188-118.eu-central-1.compute.internal:_connect] Pod 'ip-10-0-188-118-sos-collector' successfully deployed, waiting for pod to enter ready state
[ip-10-0-213-88.eu-central-1.compute.internal:run_command] Running command hostname
[ip-10-0-188-118.eu-central-1.compute.internal:run_command] Running command hostname
[ip-10-0-148-212.eu-central-1.compute.internal:run_command] Running command hostname
[ip-10-0-213-88.eu-central-1.compute.internal:_get_hostname] Hostname set to ip-10-0-213-88.eu-central-1.compute.internal
[ip-10-0-213-88.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-213-88.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-213-88.eu-central-1.compute.internal:run_command] Running command cat /etc/os-release
[ip-10-0-188-118.eu-central-1.compute.internal:_get_hostname] Hostname set to ip-10-0-188-118.eu-central-1.compute.internal
[ip-10-0-188-118.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-188-118.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-188-118.eu-central-1.compute.internal:run_command] Running command cat /etc/os-release
[ip-10-0-148-212.eu-central-1.compute.internal:_get_hostname] Hostname set to ip-10-0-148-212.eu-central-1.compute.internal
[ip-10-0-148-212.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-148-212.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-148-212.eu-central-1.compute.internal:run_command] Running command cat /etc/os-release
No nodes connected. Aborting...
```
2 nodes
```
Connecting to nodes...
[ip-10-0-188-118.eu-central-1.compute.internal:_connect] Starting sos collector container 'ip-10-0-188-118-sos-collector'
[ip-10-0-148-212.eu-central-1.compute.internal:_connect] Starting sos collector container 'ip-10-0-148-212-sos-collector'
[ip-10-0-213-88.eu-central-1.compute.internal:_connect] Starting sos collector container 'ip-10-0-213-88-sos-collector'
[ip-10-0-188-118.eu-central-1.compute.internal:_connect] Pod 'ip-10-0-188-118-sos-collector' successfully deployed, waiting for pod to enter ready state
[ip-10-0-213-88.eu-central-1.compute.internal:_connect] Pod 'ip-10-0-213-88-sos-collector' successfully deployed, waiting for pod to enter ready state
[ip-10-0-148-212.eu-central-1.compute.internal:_connect] Pod 'ip-10-0-148-212-sos-collector' successfully deployed, waiting for pod to enter ready state
[ip-10-0-188-118.eu-central-1.compute.internal:run_command] Running command hostname
[ip-10-0-148-212.eu-central-1.compute.internal:run_command] Running command hostname
[ip-10-0-188-118.eu-central-1.compute.internal:_get_hostname] Hostname set to ip-10-0-188-118.eu-central-1.compute.internal
[ip-10-0-188-118.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-188-118.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-188-118.eu-central-1.compute.internal:run_command] Running command cat /etc/os-release
[ip-10-0-148-212.eu-central-1.compute.internal:_get_hostname] Hostname set to ip-10-0-148-212.eu-central-1.compute.internal
[ip-10-0-148-212.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-148-212.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-148-212.eu-central-1.compute.internal:run_command] Running command cat /etc/os-release
[ip-10-0-213-88.eu-central-1.compute.internal:run_command] Running command hostname
[ip-10-0-213-88.eu-central-1.compute.internal:_get_hostname] Hostname set to ip-10-0-213-88.eu-central-1.compute.internal
[ip-10-0-213-88.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-213-88.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-213-88.eu-central-1.compute.internal:run_command] Running command cat /etc/os-release
[ip-10-0-213-88.eu-central-1.compute.internal:read_file] Exception while reading /etc/os-release: The command was not found or was not executable: oc.
[ip-10-0-148-212.eu-central-1.compute.internal:determine_host_policy] loaded policy Red Hat Enterprise Linux for host
[ip-10-0-188-118.eu-central-1.compute.internal:determine_host_policy] loaded policy Red Hat Enterprise Linux for host
[ip-10-0-148-212.eu-central-1.compute.internal:_load_sos_info] sos version is 4.1
[ip-10-0-188-118.eu-central-1.compute.internal:_load_sos_info] sos version is 4.1
[ip-10-0-148-212.eu-central-1.compute.internal:run_command] Running command sos report -l
[ip-10-0-188-118.eu-central-1.compute.internal:run_command] Running command sos report -l
[ip-10-0-213-88.eu-central-1.compute.internal:determine_host_policy] loaded policy Ubuntu for host
[ip-10-0-213-88.eu-central-1.compute.internal:_load_sos_info] sos is not installed on this node
connect exception: can't set attribute
[ip-10-0-148-212.eu-central-1.compute.internal:run_command] Running command sos report --list-presets
[ip-10-0-188-118.eu-central-1.compute.internal:run_command] Running command sos report --list-presets
NODE ('ip-10-0-148-212.eu-central-1.compute.internal', None) connected True
NODE ('ip-10-0-188-118.eu-central-1.compute.internal', None) connected True

Beginning collection of sosreports from 2 nodes, collecting a maximum of 4 concurrently
```
1 node
```
Connecting to nodes...
[ip-10-0-148-212.eu-central-1.compute.internal:_connect] Starting sos collector container 'ip-10-0-148-212-sos-collector'
[ip-10-0-213-88.eu-central-1.compute.internal:_connect] Starting sos collector container 'ip-10-0-213-88-sos-collector'
[ip-10-0-188-118.eu-central-1.compute.internal:_connect] Starting sos collector container 'ip-10-0-188-118-sos-collector'
[ip-10-0-148-212.eu-central-1.compute.internal:_connect] Pod 'ip-10-0-148-212-sos-collector' successfully deployed, waiting for pod to enter ready state
[ip-10-0-213-88.eu-central-1.compute.internal:_connect] Pod 'ip-10-0-213-88-sos-collector' successfully deployed, waiting for pod to enter ready state
[ip-10-0-188-118.eu-central-1.compute.internal:_connect] Pod 'ip-10-0-188-118-sos-collector' successfully deployed, waiting for pod to enter ready state
[ip-10-0-148-212.eu-central-1.compute.internal:run_command] Running command hostname
[ip-10-0-148-212.eu-central-1.compute.internal:_get_hostname] Hostname set to ip-10-0-148-212.eu-central-1.compute.internal
[ip-10-0-148-212.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-148-212.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-148-212.eu-central-1.compute.internal:run_command] Running command cat /etc/os-release
[ip-10-0-213-88.eu-central-1.compute.internal:run_command] Running command hostname
[ip-10-0-188-118.eu-central-1.compute.internal:run_command] Running command hostname
[ip-10-0-188-118.eu-central-1.compute.internal:__init__] Unable to open remote session: The command was not found or was not executable: oc.
connect exception: The command was not found or was not executable: oc.
[ip-10-0-213-88.eu-central-1.compute.internal:_get_hostname] Hostname set to ip-10-0-213-88.eu-central-1.compute.internal
[ip-10-0-213-88.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-213-88.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-213-88.eu-central-1.compute.internal:run_command] Running command cat /etc/os-release
[ip-10-0-213-88.eu-central-1.compute.internal:read_file] Exception while reading /etc/os-release: The command was not found or was not executable: oc.
[ip-10-0-148-212.eu-central-1.compute.internal:determine_host_policy] loaded policy Red Hat Enterprise Linux for host
[ip-10-0-148-212.eu-central-1.compute.internal:_load_sos_info] sos version is 4.1
[ip-10-0-148-212.eu-central-1.compute.internal:run_command] Running command sos report -l
[ip-10-0-213-88.eu-central-1.compute.internal:determine_host_policy] loaded policy Ubuntu for host
[ip-10-0-213-88.eu-central-1.compute.internal:_load_sos_info] sos is not installed on this node
connect exception: can't set attribute
[ip-10-0-148-212.eu-central-1.compute.internal:run_command] Running command sos report --list-presets
NODE ('ip-10-0-148-212.eu-central-1.compute.internal', None) connected True

Beginning collection of sosreports from 1 nodes, collecting a maximum of 4 concurrently
```

I added `NEW PATH: ` log for every time policy updates PATH, in case it'll help (for `oc` to be available on my local node `/usr/local/bin` is required)
```
Connecting to nodes...
[ip-10-0-148-212.eu-central-1.compute.internal:_connect] Starting sos collector container 'ip-10-0-148-212-sos-collector'
[ip-10-0-213-88.eu-central-1.compute.internal:_connect] Starting sos collector container 'ip-10-0-213-88-sos-collector'
[ip-10-0-188-118.eu-central-1.compute.internal:_connect] Starting sos collector container 'ip-10-0-188-118-sos-collector'
[ip-10-0-188-118.eu-central-1.compute.internal:_connect] Pod 'ip-10-0-188-118-sos-collector' successfully deployed, waiting for pod to enter ready state
[ip-10-0-148-212.eu-central-1.compute.internal:_connect] Pod 'ip-10-0-148-212-sos-collector' successfully deployed, waiting for pod to enter ready state
[ip-10-0-213-88.eu-central-1.compute.internal:_connect] Pod 'ip-10-0-213-88-sos-collector' successfully deployed, waiting for pod to enter ready state
[ip-10-0-148-212.eu-central-1.compute.internal:run_command] Running command hostname
[ip-10-0-188-118.eu-central-1.compute.internal:run_command] Running command hostname
[ip-10-0-148-212.eu-central-1.compute.internal:_get_hostname] Hostname set to ip-10-0-148-212.eu-central-1.compute.internal
[ip-10-0-148-212.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-148-212.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-148-212.eu-central-1.compute.internal:run_command] Running command cat /etc/os-release
[ip-10-0-188-118.eu-central-1.compute.internal:_get_hostname] Hostname set to ip-10-0-188-118.eu-central-1.compute.internal
[ip-10-0-188-118.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-188-118.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-188-118.eu-central-1.compute.internal:run_command] Running command cat /etc/os-release
[ip-10-0-213-88.eu-central-1.compute.internal:run_command] Running command hostname
NEW PATH: /bin:/sbin:/usr/bin:/usr/sbin
NEW PATH: /bin:/sbin:/usr/bin:/usr/sbin
[ip-10-0-213-88.eu-central-1.compute.internal:_get_hostname] Hostname set to ip-10-0-213-88.eu-central-1.compute.internal
[ip-10-0-213-88.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-213-88.eu-central-1.compute.internal:read_file] Reading file /etc/os-release
[ip-10-0-213-88.eu-central-1.compute.internal:run_command] Running command cat /etc/os-release
[ip-10-0-213-88.eu-central-1.compute.internal:read_file] Exception while reading /etc/os-release: The command was not found or was not executable: oc.
NEW PATH: /usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/sbin:/usr/local/bin
NEW PATH: /usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/sbin:/usr/local/bin:/snap/bin
NEW PATH: /usr/sbin:/usr/bin:/root/bin:/usr/local/bin:/usr/local/sbin
[ip-10-0-188-118.eu-central-1.compute.internal:determine_host_policy] loaded policy Red Hat Enterprise Linux for host
NEW PATH: /usr/sbin:/usr/bin:/root/bin:/usr/local/bin:/usr/local/sbin
[ip-10-0-148-212.eu-central-1.compute.internal:determine_host_policy] loaded policy Red Hat Enterprise Linux for host
[ip-10-0-188-118.eu-central-1.compute.internal:_load_sos_info] sos version is 4.1
[ip-10-0-148-212.eu-central-1.compute.internal:_load_sos_info] sos version is 4.1
[ip-10-0-188-118.eu-central-1.compute.internal:run_command] Running command sos report -l
[ip-10-0-148-212.eu-central-1.compute.internal:run_command] Running command sos report -l
[ip-10-0-213-88.eu-central-1.compute.internal:determine_host_policy] loaded policy Ubuntu for host
[ip-10-0-213-88.eu-central-1.compute.internal:_load_sos_info] sos is not installed on this node
connect exception: can't set attribute
[ip-10-0-148-212.eu-central-1.compute.internal:run_command] Running command sos report --list-presets
[ip-10-0-188-118.eu-central-1.compute.internal:run_command] Running command sos report --list-presets
NODE ('ip-10-0-148-212.eu-central-1.compute.internal', None) connected True
NODE ('ip-10-0-188-118.eu-central-1.compute.internal', None) connected True

Beginning collection of sosreports from 2 nodes, collecting a maximum of 4 concurrently
```
You can see that while PATH was set to `/bin:/sbin:/usr/bin:/usr/sbin` oc wasn't found and it probably prevented that single node from getting "connected"

Unfortunately I don't have more time to dig deeper, but probably we need some more tests with OCP to use sos collect

If you need more information, I'm happy to help

**Comment by TurboTurtle** [comment]
> I tried to run the latest sos collect for OCP cluster from my local machine using `bin/sos collect --no-local --batch -vvv --cluster-type ocp` command. I found a couple of errors and even fixed on my way:
> 
> 1. Cleanup problem: when sos collect fails e.g. with `No nodes connected. Aborting...`, cluster cleanup isn't called and the next run you get this error:
> 
> I solved this by adding `self.cluster.cleanup()` here https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L444 , but in general, sos collect doesn't seem to have a reliable way to cleanup, at least because there are multiple different exit points in the same function calling different shutdown functions, e.g. https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L1140 and https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L1164-L1166.
> 

Ack to adding the cluster cleanup there. As for the multiple exit points, it has to do with the use of the ThreadPoolExecutor. In order to exit out of _all_ threads when _one_ of them receives the keyboard interrupt, we have to use `os._exit()`  rather than our standard `self.exit()`. However, historically this has been beneficial as exiting in that manner on a keyboard interrupt keeps the temp dir we've been using.


> 2. Nodes are listed wrong for ocp
>    Tried to fix that: [[clusters:ocp] fix get_nodes function #2776](https://github.com/sosreport/sos/pull/2776)

Ack.

> 3. `The command was not found or was not executable: oc`

Main issue: #2775

Further issues: I suspect this is related to the sysroot problems highlighted in #2773 within the toolbox container...

> I suspect it's because of newly created policies for cluster nodes, that do this: https://github.com/sosreport/sos/blob/main/sos/policies/__init__.py#L337 and mess up my local `PATH`
> 

...and those issues may very well be related to this. We should not be modifying the local path based on remote policies, only the local policy.

> 
> You can see that while PATH was set to `/bin:/sbin:/usr/bin:/usr/sbin` oc wasn't found and it probably prevented that single node from getting "connected"
> 

Right. Part of the problem here is that historically we've restricted PATH by Policy to get as close to sure as we can be that we're not running arbitrary executables for collections. With the advent of "bring your own executables" style hosts, this gets challenging.

I don't really have a great solution since the obvious answer is "add /usr/local" to Policy PATHs, but "don't use /usr/local" has been a long standing tenant. Maybe that's no longer applicable? Or it is and we need to do some fancy footwork here? I'm open to suggestions on this front.

**Comment by npinaeva** [comment]
> Right. Part of the problem here is that historically we've restricted PATH by Policy to get as close to sure as we can be that we're not running arbitrary executables for collections. With the advent of "bring your own executables" style hosts, this gets challenging.
> 
> I don't really have a great solution since the obvious answer is "add /usr/local" to Policy PATHs, but "don't use /usr/local" has been a long standing tenant. Maybe that's no longer applicable? Or it is and we need to do some fancy footwork here? I'm open to suggestions on this front.

I think the problem here is that local PATH was changed based on remote Policy and not the PATH value itself, it's just an example showing that changing local PATH can prevent nodes from being connected. Because my local host Policy has different PATH and can find all the required executables, before if gets changed.

**Comment by npinaeva** [comment]
Now all the nodes are found, but collected sos archives are not full (maybe downloading problem), and some files are empty (e.g. hostname, ip_addr)
Here is the example of sos collect archive collected with `bin/sos collect --no-local --batch -vvvvv --cluster-type ocp` https://drive.google.com/file/d/1cHgHLtX6LMelVCiWF0YBCUIffGHvAGoi/view
