### ISSUE TITLE
sos_get_command_output() shlex.split() breaks with unicode on older python2

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#289]
``` python
[plugin:networking] collecting output of 'ip maddr show'
[plugin:networking] collecting output of 'ip neigh show'
[plugin:networking] collecting output of 'ethtool eth0'
Traceback (most recent call last):
  File "/usr/sbin/sosreport", line 23, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.6/site-packages/sos/sosreport.py", line 1229, in main
    sos.execute()
TypeError: execve() argument 1 must be encoded string without NULL bytes, not str

```

This is because:

```
> /usr/lib/python2.6/site-packages/sos/utilities.py(152)sos_get_command_output()
-> preexec_fn=_child_chdir)
(Pdb) print args
['t\x00\x00\x00i\x00\x00\x00m\x00\x00\x00e\x00\x00\x00o\x00\x00\x00u\x00\x00\x00t\x00\x00\x00', '\x00\x00\x003\x00\x00\x000\x00\x00\x000\x00\x00\x00s\x00\x00\x00', '\x00\x00\x00e\x00\x00\x00t\x00\x00\x00h\x00\x00\x00t\x00\x00\x00o\x00\x00\x00o\x00\x00\x00l\x00\x00\x00', '\x00\x00\x00e\x00\x00\x00t\x00\x00\x00h\x00\x00\x000\x00\x00\x00']
(Pdb) print command
timeout 300s ethtool eth0
(Pdb) shlex.split("timeout 300s ethtool eth0")
['timeout', '300s', 'ethtool', 'eth0']
(Pdb) print command
timeout 300s ethtool eth0
(Pdb) shlex.split(command)
['t\x00\x00\x00i\x00\x00\x00m\x00\x00\x00e\x00\x00\x00o\x00\x00\x00u\x00\x00\x00t\x00\x00\x00', '\x00\x00\x003\x00\x00\x000\x00\x00\x000\x00\x00\x00s\x00\x00\x00', '\x00\x00\x00e\x00\x00\x00t\x00\x00\x00h\x00\x00\x00t\x00\x00\x00o\x00\x00\x00o\x00\x00\x00l\x00\x00\x00', '\x00\x00\x00e\x00\x00\x00t\x00\x00\x00h\x00\x00\x000\x00\x00\x00']
(Pdb) shlex.split("timeout 300s ethtool eth0")
['timeout', '300s', 'ethtool', 'eth0']
(Pdb) print command
timeout 300s ethtool eth0
(Pdb) shlex.split(u"timeout 300s ethtool eth0")
['t\x00\x00\x00i\x00\x00\x00m\x00\x00\x00e\x00\x00\x00o\x00\x00\x00u\x00\x00\x00t\x00\x00\x00', '\x00\x00\x003\x00\x00\x000\x00\x00\x000\x00\x00\x00s\x00\x00\x00', '\x00\x00\x00e\x00\x00\x00t\x00\x00\x00h\x00\x00\x00t\x00\x00\x00o\x00\x00\x00o\x00\x00\x00l\x00\x00\x00', '\x00\x00\x00e\x00\x
```

**Comment by TurboTurtle** [comment]
Closing as we only support 2.7 on sos-3.x, and moving forward we're only supporting python3.
