### ISSUE TITLE
[snap] sos report doesn't work as a snap

### ISSUE THREAD

**Issue by arif-ali** [sosreport/sos#3044]
Some issues observed with the recent released snap

## issues

1.  It is not finding the sos module
```
root@focal-test:~# /snap/bin/sos report
Traceback (most recent call last):
  File "/snap/sosreport/22/bin/sos", line 15, in <module>
    from sos import SoS
ModuleNotFoundError: No module named 'sos'
```

2. After working around the above issue

```
Traceback (most recent call last):
  File "/snap/sosreport/22/bin/sos", line 21, in <module>
    sos = SoS(sys.argv[1:])
  File "/snap/sosreport/current/lib/python3.10/site-packages/sos/__init__.py", line 60, in __init__
    import sos.report
  File "/snap/sosreport/current/lib/python3.10/site-packages/sos/report/__init__.py", line 19, in <module>
    import sos.report.plugins
  File "/snap/sosreport/current/lib/python3.10/site-packages/sos/report/plugins/__init__.py", line 13, in <module>
    from sos.utilities import (sos_get_command_output, import_module, grep,
  File "/snap/sosreport/current/lib/python3.10/site-packages/sos/utilities.py", line 22, in <module>
    import magic
  File "/snap/sosreport/current/usr/lib/python3/dist-packages/magic/__init__.py", line 208, in <module>
    libmagic = loader.load_lib()
  File "/snap/sosreport/current/usr/lib/python3/dist-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

## resolution

1.

We need to update the snapcraft.yaml to use python3.10 and not python3.8

2.

Although `python3-libmagic` is part of the snap, but still not able to proceed. This will need further diagnosis

## testing

We need to ensure that somehow the cirrus testing is done such that the PYTHONPATH is being used from the snap, rather than system, and could be getting confused. I will need to find further details on how best we can do this.

**Comment by TurboTurtle** [comment]
Regarding the testing issue, we may want to investigate if setting a new PYTHONPATH is strictly needed at this point. If we're only testing system-installed (be it rpm, snap, or otherwise) and not from the checkout, it may be superfluous now. I'm honestly not sure off the top of my head either way.

May also be beneficial to look at wrapping the calls to avocado in a bash wrapper...

**Comment by arif-ali** [comment]
* I've submitted the above PR for 1
* I have also back-ported the magic check to 4.4 as a temporary measure for the stable snap, until I can figure out the issue

So both the stable and edge snap show the warning message that magic library isn't coming through. I'll open a new issue on that, and work my way through it.

And in terms of testing aspects. I will do some debugging/testing internally and get back with a proposal. I think installing the snap via `--dangerous` flag may mask the overall issue and is actually then using the system python, rather than the python from the snap. We may need an alternative method for testing so that this kind of thing can be easily flagged up.
