### ISSUE TITLE
[ceph] regression: cannot collect log files for package based deployments

### ISSUE THREAD

**Issue by nobuto-m** [sosreport/sos#3100]
#3092 brought some changes with regards to log paths based on Ceph versions. However, it made logs collected in the previous revisions disappear from sosreport.

On a Ceph OSD node with Ubuntu for example,
```
$ ceph --version
ceph version 17.2.0 (43e2e60a7559d3f46c9d53f1ca875fd499a1e35e) quincy (stable)

$ ./bin/sos report --batch -v --label "$(git rev-parse --short HEAD)"
```

With 699654ad,
```
$ grep /var/log/ceph sosreport-$HOSTNAME-699654ad-$(date -Idate)-*/sos_logs/sos.log
2023-01-04 01:15:39,361 INFO: [plugin:ceph_osd] collecting path '/var/log/ceph/ceph-volume.log'
2023-01-04 01:15:39,361 DEBUG: [plugin:ceph_osd] copying path '/var/log/ceph/ceph-volume.log' to archive:'/var/log/ceph/ceph-volume.log'
2023-01-04 01:15:39,362 INFO: [plugin:ceph_osd] collecting path '/var/log/ceph/ceph-osd.1.log'
2023-01-04 01:15:39,362 DEBUG: [plugin:ceph_osd] copying path '/var/log/ceph/ceph-osd.1.log' to archive:'/var/log/ceph/ceph-osd.1.log'
```
-> OSD logs are collected.
[sosreport-epic-adder-699654ad-2023-01-04-wnglymy.tar.gz](https://github.com/sosreport/sos/files/10340864/sosreport-epic-adder-699654ad-2023-01-04-wnglymy.tar.gz)

With 9c60afed,
```
$ grep /var/log/ceph sosreport-$HOSTNAME-9c60afed-$(date -Idate)-*/sos_logs/sos.log
[empty]
```
-> no OSD logs are collected.
[sosreport-epic-adder-9c60afed-2023-01-04-djnwwav.tar.gz](https://github.com/sosreport/sos/files/10340865/sosreport-epic-adder-9c60afed-2023-01-04-djnwwav.tar.gz)

My gut feeling is that the condition in the following part is not strictly tied to Ceph versions actually but rather tied to deployment methods such as package based, ceph-ansible container based, or cephadm container based as I commented in https://github.com/sosreport/sos/pull/3099#discussion_r1060417179

https://github.com/sosreport/sos/blob/9c60afed25c6cd8ecbd25c52a403376262a121d2/sos/report/plugins/ceph_osd.py#L44-L69

**Comment by TurboTurtle** [comment]
Hmm. Ok, so my understanding was/is that with ceph version 16+, the host file paths are something like `/var/log/ceph/<fsid>/osd/blah`, which were earlier just `/var/log/ceph/osd/blah`. These newer paths  then get volume-mounted into the relevant containers at the previous (no fsid) paths.

I guess this comes down to - are there deployments with the current version of ceph where it is `/var/log/ceph/blah/` (no fsid subdir) for *both* the host and the container paths? If so, how does one differentiate between deployment styles?

**Comment by nobuto-m** [comment]
From a Ceph process point of view, it just writes logs to `/var/log/ceph` without fsid if I'm not mistaken. Adding a fsid into log_dir is cephadm's nice feature to accommodate multiple Ceph clusters on a single host if I understand it correctly. If a Ceph process running on the host, no fsid is added to the path.
https://github.com/ceph/ceph/blob/7d4812b52eef8035abc273c3e83c8c156b12c51b/src/cephadm/cephadm.py#L2279-L2281

Can it be like `/var/log/ceph/**/ceph-osd*.log` so necessary logs can be collected regardless of the deployment methods? I'm not sure about the right wildcard syntax in the sosreport though.

For the record, the example in the description was with Ceph version 17.2.0 (>=16) running on the host (without containers).

**Comment by TurboTurtle** [comment]
I believe `/var/log/ceph/**/ceph-osd*.log` _should_ work here, as internally `add_copy_spec()` expands paths with `glob.glob(copyspec, recursive=True)`

The environments I have available to me are all deployed as `/var/log/ceph/<fsid>/`, so I can test on that front - if you could test the `**` wildcard on your end that'd be helpful. If this satisfies both deployments, it'll make the plugins easier to read for collections at the very least.

**Comment by nkshirsagar** [comment]
I'm running sos on a osd node, running ceph quinch,

```
ubuntu@nkshirsagar-bastion:~/stsstack-bundles/ceph$ juju ssh ceph-osd/0 sudo -s
root@juju-ecb8f3-default-1:/home/ubuntu# dpkg -l | grep ceph
ii  ceph                            17.2.0-0ubuntu0.22.04.2~cloud0    amd64        distributed storage and file system
ii  ceph-base                       17.2.0-0ubuntu0.22.04.2~cloud0    amd64        common ceph daemon libraries and management tools
ii  ceph-common                     17.2.0-0ubuntu0.22.04.2~cloud0    amd64        common utilities to mount and interact with a ceph storage cluster
ii  ceph-mds                        17.2.0-0ubuntu0.22.04.2~cloud0    amd64        metadata server for the ceph distributed file system
ii  ceph-mgr                        17.2.0-0ubuntu0.22.04.2~cloud0    amd64        manager for the ceph distributed file system
ii  ceph-mgr-modules-core           17.2.0-0ubuntu0.22.04.2~cloud0    all          ceph manager modules which are always enabled
ii  ceph-mon                        17.2.0-0ubuntu0.22.04.2~cloud0    amd64        monitor server for the ceph storage system
ii  ceph-osd                        17.2.0-0ubuntu0.22.04.2~cloud0    amd64        OSD server for the ceph storage system
ii  ceph-volume                     17.2.0-0ubuntu0.22.04.2~cloud0    all          tool to facilidate OSD deployment
ii  libcephfs2                      17.2.0-0ubuntu0.22.04.2~cloud0    amd64        Ceph distributed file system client library
ii  libsqlite3-mod-ceph             17.2.0-0ubuntu0.22.04.2~cloud0    amd64        SQLite3 VFS for Ceph
ii  python3-ceph-argparse           17.2.0-0ubuntu0.22.04.2~cloud0    amd64        Python 3 utility libraries for Ceph CLI
ii  python3-ceph-common             17.2.0-0ubuntu0.22.04.2~cloud0    all          Python 3 utility libraries for Ceph
ii  python3-cephfs                  17.2.0-0ubuntu0.22.04.2~cloud0    amd64        Python 3 libraries for the Ceph libcephfs library
root@juju-ecb8f3-default-1:/home/ubuntu# cd /var/log/ceph/
root@juju-ecb8f3-default-1:/var/log/ceph# ls
ceph-osd.0.log  ceph-volume.log
```

I cloned latest sosreport, 

```
commit 9c60afed25c6cd8ecbd25c52a403376262a121d2 (HEAD -> main, origin/main, origin/HEAD)
Author: Jake Hunsaker <jhunsake@redhat.com>
Date:   Fri Dec 16 14:23:06 2022 -0500

    [ceph_mgr] Update plugin for newer versions of Ceph
    
    Updates the plugin to account for newer versions of Ceph, similar to the
    previous few commits focusing on the ceph plugins.
    
    Signed-off-by: Jake Hunsaker <jhunsake@redhat.com>

```

and ran 

```
root@juju-ecb8f3-default-1:/home/ubuntu/sos/sos/bin# ./sos report

sosreport (version 4.4)

This command will collect system configuration and diagnostic
information from this Ubuntu system.

For more information on Canonical visit:

        Community Website  : https://www.ubuntu.com/
        Commercial Support : https://www.canonical.com

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.


Press ENTER to continue, or CTRL-C to quit.
```

I do see the OSD log files collected,

```
root@juju-ecb8f3-default-1:/tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-ttlexem/var/log/ceph# ls /var/log/ceph/ceph-
ceph-osd.0.log   ceph-volume.log  

root@juju-ecb8f3-default-1:/tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-ttlexem/var/log/ceph# ls
ceph-osd.0.log  ceph-volume.log
root@juju-ecb8f3-default-1:/tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-ttlexem/var/log/ceph# pwd
/tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-ttlexem/var/log/ceph
```

What am I missing here? I am not able to reproduce the issue @nobuto-m is able to..

**Comment by nobuto-m** [comment]
> `root@juju-ecb8f3-default-1:/home/ubuntu/sos/sos/bin# ./sos report`

What happens if you use `./bin/sos`? I suppose the current directory you are on matters.

**Comment by nkshirsagar** [comment]
Yes now the collected sosreport does not container the /var/log/ceph folder at all!

~~~
root@juju-ecb8f3-default-1:/home/ubuntu/sos/sos# bin/sos report

WARNING: Failed to load 'magic' module version >= 0.4.20 which sos aims
to use for detecting binary files. A less effective method will be used.
It is recommended to install proper python3-magic package with the
module.

^Croot@juju-ecb8f3-default-1:/home/ubuntu/sos/sos# cd bin
root@juju-ecb8f3-default-1:/home/ubuntu/sos/sos/bin# ./sos report

sosreport (version 4.4)

This command will collect system configuration and diagnostic
information from this Ubuntu system.

For more information on Canonical visit:

        Community Website  : https://www.ubuntu.com/
        Commercial Support : https://www.canonical.com

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.


Press ENTER to continue, or CTRL-C to quit.

<snip>

root@juju-ecb8f3-default-1:/tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-xzxqrjf/var/log# ls
apt  auth.log  cloud-init-output.log  cloud-init.log  dist-upgrade  dmesg  dpkg.log  juju  kern.log  syslog  ubuntu-advantage.log  unattended-upgrades
root@juju-ecb8f3-default-1:/tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-xzxqrjf/var/log# cd ceph
bash: cd: ceph: No such file or directory

root@juju-ecb8f3-default-1:/tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-xzxqrjf/sos_commands# ls /var/log/ceph/
ceph-osd.0.log  ceph-volume.log
root@juju-ecb8f3-default-1:/tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-xzxqrjf/sos_commands# cd ..
root@juju-ecb8f3-default-1:/tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-xzxqrjf# find . -name ceph-osd.0.log
root@juju-ecb8f3-default-1:/tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-xzxqrjf# 

~~~
That's strange, but yes I do see the warning for the magic issue only when I run it as bin/sos report and not cd bin; ./sos report
so obviously when I run ./sos report from /home/ubuntu/sos/sos/bin its not the same as running bin/sos report from /home/ubuntu/sos/sos

~~~
root@juju-ecb8f3-default-1:/home/ubuntu/sos/sos# bin/sos report

WARNING: Failed to load 'magic' module version >= 0.4.20 which sos aims
to use for detecting binary files. A less effective method will be used.
It is recommended to install proper python3-magic package with the
module.


sosreport (version 4.4)

^C
Exiting on user cancel
root@juju-ecb8f3-default-1:/home/ubuntu/sos/sos# cd bin
root@juju-ecb8f3-default-1:/home/ubuntu/sos/sos/bin# ./sos report

sosreport (version 4.4)

This command will collect system configuration and diagnostic
information from this Ubuntu system.

For more information on Canonical visit:

        Community Website  : https://www.ubuntu.com/
        Commercial Support : https://www.canonical.com

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.


Press ENTER to continue, or CTRL-C to quit.
^CExiting on user cancel
~~~

I also tested with /var/log/ceph/**/ceph-osd*.log, it works..

~~~

root@juju-ecb8f3-default-1:/home/ubuntu/sos/sos# git diff
diff --git a/sos/report/plugins/ceph_osd.py b/sos/report/plugins/ceph_osd.py
index 37109125..557791b6 100644
--- a/sos/report/plugins/ceph_osd.py
+++ b/sos/report/plugins/ceph_osd.py
@@ -64,8 +64,8 @@ class CephOSD(Plugin, RedHatPlugin, UbuntuPlugin):
         self.add_copy_spec([
             f"{rundir}/ceph-osd*",
             f"{libdir}/**/kv_backend",
-            f"{logdir}/ceph-osd*.log",
-            f"{logdir}/ceph-volume*.log",
+            "/var/log/ceph/**/ceph-osd*.log",
+            "/var/log/ceph/**/ceph-volume*.log",
         ])
 
         self.add_cmd_output([


root@juju-ecb8f3-default-1:/home/ubuntu/sos/sos# bin/sos report

WARNING: Failed to load 'magic' module version >= 0.4.20 which sos aims
to use for detecting binary files. A less effective method will be used.
It is recommended to install proper python3-magic package with the
module.

sosreport (version 4.4)

This command will collect system configuration and diagnostic
information from this Ubuntu system.

For more information on Canonical visit:

        Community Website  : https://www.ubuntu.com/
        Commercial Support : https://www.canonical.com

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.


Press ENTER to continue, or CTRL-C to quit.

Optionally, please enter the case id that you are generating this report for []: 

 Setting up archive ...
 Setting up plugins ...
[plugin:firewall_tables] skipped command 'nft list ruleset': required kmods missing: nf_tables, nfnetlink.   Use '--allow-system-changes' to enable collection.
[plugin:firewall_tables] skipped command 'iptables -vnxL': required kmods missing: nf_tables, iptable_filter.  
[plugin:firewall_tables] skipped command 'ip6tables -vnxL': required kmods missing: nf_tables, ip6table_filter.  
[plugin:lxd] skipped command 'lxd.buginfo': required kmods missing: ip6table_mangle, nf_tables, iptable_mangle, ip6table_nat, iptable_filter, ip6table_raw, iptable_raw, ip6_tables, ebtable_filter, ebtables, ip6table_filter.  
[plugin:networking] skipped command 'ip -s macsec show': required kmods missing: macsec.   Use '--allow-system-changes' to enable collection.
[plugin:networking] skipped command 'ss -peaonmi': required kmods missing: unix_diag, tcp_diag, af_packet_diag, inet_diag, xsk_diag, udp_diag, netlink_diag.   Use '--allow-system-changes' to enable collection.
[plugin:ufw] skipped command 'ufw status numbered': required kmods missing: iptable_filter.  
[plugin:ufw] skipped command 'ufw app list': required kmods missing: iptable_filter.  
 Running plugins. Please wait ...

  Finishing plugins              [Running: ubuntu]                                        
  Finished running plugins                                                               
Creating compressed archive...

Your sosreport has been generated and saved in:
	/tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-upjvztu.tar.xz

 Size	2.99MiB
 Owner	root
 sha256	6597cd1ec93d47ba918f33486430e5d8d30b0aee075d03418346e58f307e506b

Please send this file to your support representative.

root@juju-ecb8f3-default-1:/home/ubuntu/sos/sos# hotname


root@juju-ecb8f3-default-1:/home/ubuntu/sos/sos# ls /tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-upjvztu/var/log/ceph/ceph-
ceph-osd.0.log   ceph-volume.log  
root@juju-ecb8f3-default-1:/home/ubuntu/sos/sos# ls /tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-upjvztu/var/log/ceph/ceph-*
/tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-upjvztu/var/log/ceph/ceph-osd.0.log  /tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-upjvztu/var/log/ceph/ceph-volume.log

root@juju-ecb8f3-default-1:/tmp/sosreport-juju-ecb8f3-default-1-2023-01-05-upjvztu# ls var/log/ceph/ceph-*
var/log/ceph/ceph-osd.0.log  var/log/ceph/ceph-volume.log
~~~

**Comment by nobuto-m** [comment]
Yes, `**` seems to be working for add_copy_spec. But it wasn't as simple as putting `**` everywhere since `add_file_tags` doesn't seem to accept `**`.

```python
Traceback (most recent call last):
  File "/root/sos/sos/report/__init__.py", line 1217, in setup
    plug.setup()
  File "/root/sos/sos/report/plugins/ceph_mgr.py", line 57, in setup
    self.add_copy_spec([
  File "/root/sos/sos/report/plugins/__init__.py", line 1737, in add_copy_spec
    _spec_tags.extend(self.get_tags_for_file(files[0]))
  File "/root/sos/sos/report/plugins/__init__.py", line 1610, in get_tags_for_file
    if re.match(key, fname):
  File "/usr/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 671, in _parse
    raise source.error("multiple repeat",
re.error: multiple repeat at position 15
```

This test commit is JFYI:
https://github.com/nobuto-m/sos/commit/1d428bd096628d38206a5441cb84ec8d136748b9


P.S.
> That's strange, but yes I do see the warning for the magic issue only when I run it as bin/sos report and not cd bin; ./sos report
> so obviously when I run ./sos report from /home/ubuntu/sos/sos/bin its not the same as running bin/sos report from /home/ubuntu/sos/sos

I think it's because you have sosreport installed on the system. With `./sos report`, the command cannot find libraries from the current directory so the system ones are used instead.

**Comment by nkshirsagar** [comment]
> Yes, `**` seems to be working for add_copy_spec. But it wasn't as simple as putting `**` everywhere since `add_file_tags` doesn't seem to accept `**`.

I'm not sure what the tags are used for, but I think we could do without the tags if its an issue adding it with ** , @TurboTurtle @pmoravec any thoughts?
> 
> ```python
> Traceback (most recent call last):
>   File "/root/sos/sos/report/__init__.py", line 1217, in setup
>     plug.setup()
>   File "/root/sos/sos/report/plugins/ceph_mgr.py", line 57, in setup
>     self.add_copy_spec([
>   File "/root/sos/sos/report/plugins/__init__.py", line 1737, in add_copy_spec
>     _spec_tags.extend(self.get_tags_for_file(files[0]))
>   File "/root/sos/sos/report/plugins/__init__.py", line 1610, in get_tags_for_file
>     if re.match(key, fname):
>   File "/usr/lib/python3.8/re.py", line 191, in match
>     return _compile(pattern, flags).match(string)
>   File "/usr/lib/python3.8/re.py", line 304, in _compile
>     p = sre_compile.compile(pattern, flags)
>   File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
>     p = sre_parse.parse(p, flags)
>   File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
>     p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
>   File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
>     itemsappend(_parse(source, state, verbose, nested + 1,
>   File "/usr/lib/python3.8/sre_parse.py", line 671, in _parse
>     raise source.error("multiple repeat",
> re.error: multiple repeat at position 15
> ```
> 
> This test commit is JFYI: [nobuto-m@1d428bd](https://github.com/nobuto-m/sos/commit/1d428bd096628d38206a5441cb84ec8d136748b9)
> 
> P.S.
> 
> > That's strange, but yes I do see the warning for the magic issue only when I run it as bin/sos report and not cd bin; ./sos report
> > so obviously when I run ./sos report from /home/ubuntu/sos/sos/bin its not the same as running bin/sos report from /home/ubuntu/sos/sos
> 
> I think it's because you have sosreport installed on the system. With `./sos report`, the command cannot find libraries from the current directory so the system ones are used instead.

Yes, you are right.

**Comment by TurboTurtle** [comment]
The tags are for the manifest that gets generated along with the report - it is primarily used by automation to more reliably find specific data rather than relying directly on filenames which may change (for example, when command options change, the filename will change as well).

The file tags patterns use regexes, not globs. So we could replace something like 

```python
self.add_file_tags({
    f'{logdir}/ceph-mgr.*.log': 'ceph_mgr_log',
    [...]
```

with 

```python
self.add_file_tags({
    '/var/log/ceph(.*)?/ceph-mgr.*.log': 'ceph_mgr_log',
    [...]
```

It's a little disjointed here between `add_file_tags()` and `add_copy_spec()`, yes, but `add_copy_spec()` uses globs to more naturally accept wildcard paths from sysadmins or support engineers. Conversely, `add_file_tags()` uses regex as it is the more flexible way to pattern match to make tagging assignments.
