### ISSUE TITLE
[testing][snap] improve testing for snaps

### ISSUE THREAD

**Issue by arif-ali** [sosreport/sos#3126]
As we were prepping for testing of the 4.5.0 snap, found an issue where `sos` doesn't work on ubuntu 18.04. This therefore means the cirrus CI test for 18.04 hasn't actually worked, and has given a false positive.

We should have seen the following error in the testing
```
Traceback (most recent call last):
  File "/snap/sosreport/70/bin/sos", line 21, in <module>
    sos = SoS(sys.argv[1:])
  File "/snap/sosreport/70/lib/python3.10/site-packages/sos/__init__.py", line 72, in __init__
    import sos.collector
  File "/snap/sosreport/70/lib/python3.10/site-packages/sos/collector/__init__.py", line 29, in <module>
    from sos.collector.sosnode import SosNode
  File "/snap/sosreport/70/lib/python3.10/site-packages/sos/collector/sosnode.py", line 17, in <module>
    from pkg_resources import parse_version
  File "/snap/sosreport/70/lib/python3.10/site-packages/pkg_resources/__init__.py", line 82, in <module>
    from pkg_resources.extern import platformdirs
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "/snap/sosreport/70/lib/python3.10/site-packages/pkg_resources/extern/__init__.py", line 52, in create_module
    return self.load_module(spec.name)
  File "/snap/sosreport/70/lib/python3.10/site-packages/pkg_resources/extern/__init__.py", line 37, in load_module
    __import__(extant)
  File "/snap/sosreport/70/lib/python3.10/site-packages/pkg_resources/_vendor/platformdirs/__init__.py", line 5
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

Internal testing now, and adding the below diff has resolved the above error.

```diff
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index 2fe65699..fe1b860c 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -9,7 +9,7 @@ base: core22
 confinement: classic
 adopt-info: sos
 environment:
-  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages:${PYTHONPATH}
+  PYTHONPATH: ${SNAP}/usr/lib/python3.10:${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages:${PYTHONPATH}
 
 parts:
   sos:
@@ -25,6 +25,7 @@ parts:
       - gettext
     stage-packages:
       - python3-venv
+      - libpython3.10-minimal
     python-packages:
       - pip
       - setuptools
```

But, now getting

```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
Traceback (most recent call last):
  File "/snap/sosreport/x1/usr/lib/python3.10/encodings/__init__.py", line 85, in search_function
  File "/snap/sosreport/x1/usr/lib/python3.10/encodings/__init__.py", line 64, in normalize_encoding
AttributeError: 'str' object has no attribute 'isascii'
Aborted (core dumped)
```

But, nevertheless better testing is required, and will come up with something better for future, and will submit PR for the snap fixes once we've debugged the issue

**Comment by arif-ali** [comment]
Seems like [this](https://github.com/sosreport/sos/commit/58118340be133ced5374fdd2004f21a05224d128) breaks the run on bionic (18.04) using snap. Tried building with bot core20 and core22, and we have the same problem.

If I revert above commit, then we have no problems at all

**Comment by arif-ali** [comment]
I have tested the following diff, and this should work

```diff
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index 2fe65699..6767f7f0 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -30,6 +30,7 @@ parts:
       - setuptools
       - wheel
       - python_magic
+      - packaging
 
 apps:
   sos:
diff --git a/sos/collector/sosnode.py b/sos/collector/sosnode.py
index 38f739d7..88d3aa6b 100644
--- a/sos/collector/sosnode.py
+++ b/sos/collector/sosnode.py
@@ -14,7 +14,7 @@ import logging
 import os
 import re
 
-from pkg_resources import parse_version
+from packaging.version import parse as parse_version
 from pipes import quote
 from sos.policies import load
 from sos.policies.init_systems import InitSystem
 ```
 
 @TurboTurtle wdyt? obviously this adds a new python library to the mix

**Comment by TurboTurtle** [comment]
Using `packaging` would add a cross-repo dependency on the RHEL downstreams, which we try to avoid. I am curious as to why `setuptools` is not providing `pkg_resources` for the snaps, but that's a question for another time.

Perhaps something like this:

```python
try:
    from pkg_resources import parse_version
except ImportError:
    from packaging.version import parse as parse_version
```

and from there we allow the specific packaging of rpm/snaps/debs/whatever to define which one they prefer.

**Comment by TurboTurtle** [comment]
Of course, the other option would be to either extract the specific `parse_version()` method we need or roll our own and do away with either dependency entirely. We only currently do this kind of version checking for `collect`, so the footprint is very small overall.

**Comment by arif-ali** [comment]
ack, let me get that tested, and see what happens.

I have pushed a PR, where I think we could of done with adding the sos alias in snap, that now reports this as an issue in stage one tests :)
