### ISSUE TITLE
parse_version fails on Ubuntu

### ISSUE THREAD

**Issue by pponnuvel** [sosreport/sos#3548]
As noted in https://github.com/sosreport/sos/issues/3544, there are several packages on Ubuntu that do not conform to PEP440.

```
Traceback (most recent call last):
  File "/home/ponnuvel/myGit/sos/sos/report/__init__.py", line 1230, in setup
    plug.setup()
  File "/home/ponnuvel/myGit/sos/sos/report/plugins/pacemaker.py", line 151, in setup
    self.setup_pcs()
  File "/home/ponnuvel/myGit/sos/sos/report/plugins/pacemaker.py", line 61, in setup_pcs
    if parse_version(pcs_version) > parse_version('0.10.8'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/packaging/version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.11.4-1ubuntu3'
```

This is from pacemaker plugin. Probably needs to be fixed in collector/clusters/pacemaker.py too.

**Comment by dnegreira** [comment]
I'll have a look

**Comment by pponnuvel** [comment]
Hi David, I have just created a PR. It basically formats to PEP440 like you've done in sos/collector/sosnode.py - just moved the function to utilities. I tested pacemaker plugin and it works with this change. Please take a look.

**Comment by dnegreira** [comment]
> Hi @dnegreira I have just created a PR. It basically formats to PEP440 like you've done in sos/collector/sosnode.py - just moved the function to utilities. I tested pacemaker plugin and it works with this change. Please take a look at #3554.

Awesome, thanks for this!
