### ISSUE TITLE
[collect] Using batch flag with password blocks requesting the ssh password

### ISSUE THREAD

**Issue by TrevorBenson** [sosreport/sos#3839]
SOS Version: sos-4.7.2-3.el9.noarch

```
$ man sos-collect |grep -A1 -e '\-\-batch$' -e '\-\-password$'
       --batch
              Run in non-interactive mode. This will skip prompts for user input, with the exception of a prompt for the SSH password.
--
       --password
              Specifying this option will cause sos collect to prompt the user for an SSH password that will be used to connect to all nodes.
```

Using `--batch --password` leads to an **unsupported operand type(s) for +: 'bool' and 'str'** error:

```
[root@localhost ~]# sos collect --batch --password --ssh-user project-user --nodes 192.168.124.121

sos-collector (version 4.7.2)

This utility is used to collect sos reports from multiple nodes simultaneously.
Remote connections are made and/or maintained to those nodes via well-known
transport protocols such as SSH.

An archive of sos report tarballs collected from the nodes will be generated in
/var/tmp/sos.mwlhdiqu and may be provided to an appropriate support
representative.

The generated archive may contain data considered sensitive and its content
should be reviewed by the originating organization before being passed to any
third party.

No configuration changes will be made to the system running this utility or
remote systems that it connects to.


The following is a list of nodes to collect from:
	localhost
	192.168.124.121


Connecting to nodes...
[192.168.124.121:__init__] Unable to open remote session: unsupported operand type(s) for +: 'bool' and 'str'
Collection would only gather from localhost due to failure to either enumerate or connect to cluster nodes. Assuming single collection from localhost is not desired.
Aborting...
```

This was found while using a fix for nested sudo in PR #3838

**Comment by jcastill** [comment]
I managed to reproduce and get a call trace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sos/collector/sosnode.py", line 89, in __init__
    self._transport.connect(self._password)
  File "/usr/lib/python3.9/site-packages/sos/collector/transports/__init__.py", line 146, in connect
    if self._connect(password):
  File "/usr/lib/python3.9/site-packages/sos/collector/transports/control_persist.py", line 134, in _connect
    res.sendline(password)
  File "/usr/lib/python3.9/site-packages/pexpect/pty_spawn.py", line 578, in sendline
    return self.send(s + self.linesep)
TypeError: unsupported operand type(s) for +: 'bool' and 'str'
[192.168.124.134:__init__] Unable to open remote session: unsupported operand type(s) for +: 'bool' and 'str'
```

And send a PR with a possible fix.

**Comment by TrevorBenson** [comment]
@jcastill Given the man page output stating that `--batch` prevents any input, except requesting the ssh password, I believe they are intended to be a functional combination.

**Comment by jcastill** [comment]
Ah, I see. Let me rework this then

**Comment by jcastill** [comment]
I guess we either change the man page, or I change this:

https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L796

```
       try:
            if ((self.opts.password or (self.opts.password_per_node and
                                        self.opts.primary))
                    and not self.opts.batch):
                self.log_debug('password specified, not using SSH keys')
                msg = ('Provide the SSH password for user '
                       f'{self.opts.ssh_user}: ')
                self.opts.password = getpass(prompt=msg)
```

But it's late here so I may be misreading the code above. I'll do some tests and do a force push, considering the man page the source of truth.

**Comment by pmoravec** [comment]
Good spot of code that would allow that. But I feel the @TrevorBenson's argument is more valid or important: `--batch` option suppresses any user input, hence making `--password` option a "no-op" one - at least that behavour would be in line with otehr options when `--batch` is used.

So I would rather vote for printing a warning an invalid combination of options is used (and resetting `--password` option to prevent the exception).

**Comment by jcastill** [comment]
ACK, and that will need a change in the man page as well to reflect this, but that can be part of this PR.

**Comment by jcastill** [comment]
@TrevorBenson indeed, sorry I missed closing this. I'll do it now.
