### ISSUE TITLE
network plugin fails if NetworkManager is disabled

### ISSUE THREAD

**Issue by sandrobonazzola** [sosreport/sos#432]
Verified 3.2-18-g8a56b5c on fedora 20:
```bash
systemctl status  NetworkManager.service
NetworkManager.service - Network Manager
   Loaded: loaded (/usr/lib/systemd/system/NetworkManager.service; disabled)
   Active: inactive (dead)

sosreport -o networking --verbose
....
[plugin:networking] collecting output of 'nmcli con show conf 'Error: nmcli (0.9.9.0) and NetworkManager (unknown) versions don't match. Force execution using --nocheck, but the results are unpredictable.''
networking
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1163, in collect
    plug.collect()
  File "/usr/lib/python2.7/site-packages/sos/plugins/__init__.py", line 630, in collect
    self._collect_cmd_output()
  File "/usr/lib/python2.7/site-packages/sos/plugins/__init__.py", line 610, in _collect_cmd_output
    timeout=timeout, runat=runat)
  File "/usr/lib/python2.7/site-packages/sos/plugins/__init__.py", line 555, in get_cmd_output_now
    result = self.get_command_output(exe, timeout=timeout, runat=runat)
  File "/usr/lib/python2.7/site-packages/sos/plugins/__init__.py", line 464, in get_command_output
    result = sos_get_command_output(prog, timeout=timeout, runat=runat)
  File "/usr/lib/python2.7/site-packages/sos/utilities.py", line 144, in sos_get_command_output
    args = shlex.split(command)
  File "/usr/lib64/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib64/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib64/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib64/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

nmcli con show conf
Error: nmcli (0.9.9.0) and NetworkManager (unknown) versions don't match. Force execution using --nocheck, but the results are unpredictable.
```

**Comment by pmoravec** [comment]
Isn't it fixed by https://github.com/pmoravec/sos/commit/d19bc046d549aaf634314a257dd22623df731648 ? So to close?

**Comment by bmr-cymru** [comment]
Yes :-)
