### ISSUE TITLE
[policy] more startup exception handling problems

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#520]
Just saw this:

```
$ sudo sosreport --list-plugins
^CTraceback (most recent call last):
  File "/sbin/sosreport", line 23, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1152, in main
    sos = SoSReport(args)
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 526, in __init__
    self.policy = sos.policies.load()
  File "/usr/lib/python2.7/site-packages/sos/policies/__init__.py", line 38, in load
    cache['policy'] = policy()
  File "/usr/lib/python2.7/site-packages/sos/policies/redhat.py", line 165, in __init__
    super(FedoraPolicy, self).__init__()
  File "/usr/lib/python2.7/site-packages/sos/policies/redhat.py", line 49, in __init__
    if self.package_manager.all_pkgs()['filesystem']['version'][0] == '3':
  File "/usr/lib/python2.7/site-packages/sos/policies/__init__.py", line 107, in all_pkgs
    self.packages = self.get_pkg_list()
  File "/usr/lib/python2.7/site-packages/sos/policies/__init__.py", line 92, in get_pkg_list
    pkg_list = shell_out(self.query_command).splitlines()
  File "/usr/lib/python2.7/site-packages/sos/utilities.py", line 171, in shell_out
    return sos_get_command_output(cmd)[1]
  File "/usr/lib/python2.7/site-packages/sos/utilities.py", line 148, in sos_get_command_output
    stdout, stderr = p.communicate()
  File "/usr/lib64/python2.7/subprocess.py", line 792, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib64/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

**Comment by TurboTurtle** [comment]
Looks to have been resolved with fbcfcc4

```
[jake@terra sos]$ sudo sosreport --list-plugins
^C[jake@terra sos]$ sudo sosreport --list-plugins

sosreport (version 3.5.1)

^CExiting on user cancel
[jake@terra sos]$ 
```
