### ISSUE TITLE
[policy] add support for OpenSuSE

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#523]
SSIA really. The SuSE stable is one of the the few major distro families that we don't yet support in sos - let's fix that.

**Comment by bmr-cymru** [comment]
```
[plugin:networking] collecting output of 'nmcli con show conf 'Error: nmcli (0.9.10.0) and NetworkManager (unknown) versions don't match. Force execution using --nocheck, but the results are unpredictable.''
Traceback (most recent call last):
  File "/usr/sbin/sosreport", line 25, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1459, in main
    sos.execute()
ValueError: No closing quotation

> /usr/lib64/python2.7/shlex.py(172)read_token()
-> raise ValueError, "No closing quotation"
```

This is on a clean from-the-ISO install of OpenSuSE 13.2 (just added git + rpmbuild from zypper)..
