### ISSUE TITLE
--all-logs option triggers error in logs plugin

### ISSUE THREAD

**Issue by karibou** [sosreport/sos#606]
When running the logs plugin with all-logs, sosreport triggers an error : 

 Setting up archive ...
 Setting up plugins ...
caught exception in plugin method "logs.setup()"
writing traceback to sos_logs/logs-plugin-errors.txt
 Running plugins. Please wait ...

Detail of the error is : 
Traceback (most recent call last):
  File "/home/ubuntu/sos/sos/sosreport.py", line 1220, in setup
    plug.setup()
  File "/home/ubuntu/sos/sos/plugins/logs.py", line 94, in setup
    super(DebianLogs, self).setup()
  File "/home/ubuntu/sos/sos/plugins/logs.py", line 46, in setup
    rsyslog_conf)
NameError: global name 'rsyslog_conf' is not defined

The rsyslog_conf variable is not defined and missing.

**Comment by karibou** [comment]
Looks like commit b3faad3f82ee1f735e2221bb2f39b8b8aeaf0e86 closed this issue.
