### ISSUE TITLE
[reporting] deal with UTF-8 characters

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#722]
If future report `sos.txt` / `sos.html` contains an UTF-8 character, sos raises uncaught exception:

    Traceback (most recent call last):
      File "./sosreport", line 25, in <module>
        main(sys.argv[1:])
      File "/home/pmoravec/sos-trunk/sos-master/sos/sos/sosreport.py", line 1617, in main
        sos.execute()
      File "/home/pmoravec/sos-trunk/sos-master/sos/sos/sosreport.py", line 1592, in execute
        self.plain_report()
      File "/home/pmoravec/sos-trunk/sos-master/sos/sos/sosreport.py", line 1342, in plain_report
        fd.write(str(PlainTextReport(report)))
      File "/home/pmoravec/sos-trunk/sos-master/sos/sos/reporting.py", line 151, in __str__
        return "\n".join(buf)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 49: ordinal not in range(128)

Reproducer: have e.g. some networking interface named in UTF-8, like `/etc/sysconfig/network-scripts/ifcfg-Svazek_připojení_1`.

Particular reproducer:
1. `LANG=cs_CZ.UTF-8 gnome-control-center`
2. Click to "síť" / network
3. Add a new bonding interface without any details (bonding = "Svazek" in CZ)
4. Run sosreport (often enough to run with o general)

How to fix this:
1) `"\n".join(buf)` needs to pass decoded UTF-8 text
2) `fd.write` needs to replace str(..) by some other function name
3) `fd.write` needs to encode UTF-8

**Comment by pmoravec** [comment]
FYI I just tested the fix on current upstream and found no issue - no regression, no `UnicodeDecodeError` (other than #835).
