### ISSUE TITLE
[xen] AttributeError: 'Xen' object has no attribute 'call_ext_prof'

### ISSUE THREAD

**Issue by wenjianhn** [sosreport/sos#914]
Traceback (most recent call last):
```
  File "/root/jacob/sosreport/sos/sosreport.py", line 1254, in setup
    plug.setup()
  File "/root/jacob/sosreport/sos/plugins/xen.py", line 90, in setup
    if self.is_running_xenstored():
  File "/root/jacob/sosreport/sos/plugins/xen.py", line 47, in is_running_xenstored
    xs_pid = self.call_ext_prof("pidof xenstored")['ouput']
AttributeError: 'Xen' object has no attribute 'call_ext_prof'
```

**Comment by bmr-cymru** [comment]
Huh, typo from June 2014 that nobody noticed for two years... I guess Xen is not so popular these days ;-)

Thanks for the pull request - I'll get this included in the next batch of merges.
