### ISSUE TITLE
[jars] traceback with python 3

### ISSUE THREAD

**Issue by sandrobonazzola** [sosreport/sos#984]
sos 3.4

# sosreport -o jars lead to:
 Setting up plugins ...
caught exception in plugin method "jars.setup()"
writing traceback to sos_logs/jars-plugin-errors.txt
content is:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/sos/sosreport.py", line 1252, in setup
    plug.setup()
  File "/usr/lib/python3.5/site-packages/sos/plugins/jars.py", line 76, in setup
    results_str = json.dumps(results, indent=4, separators=(",", ": "))
  File "/usr/lib64/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib64/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/usr/lib64/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.5/json/encoder.py", line 375, in _iterencode_dict
    raise TypeError("key " + repr(key) + " is not a string")
TypeError: key b'groupId' is not a string

**Comment by bmr-cymru** [comment]
When reporting problems with particular python versions please **always** include the exact version (inc. any distribution release string) - we run CI tests with three versions of Python and developers test with Python 2 and Python 3 for each commit and release, so "traceback with python 3" is not very useful information - clearly it doesn't happen for *all* versions of Python 3, or it would have been seen already.

I'm assuming this is 3.6 like the other rawhide one?

**Comment by bmr-cymru** [comment]
Hmm, no, according to the backtrace 3.5 (this is why it is good to always include that information clearly...).

OK. This looks like more unicode mishandling in the `jars` plugin - the data it reads from files are received as bytes (and need to be compared to, or operated on, with other bytes). When the data needs to be packed in the resulting JSON archive those values need to be strings.

**Comment by bmr-cymru** [comment]
Please test with the branch `bmr-jars-key-is-not-a-string` (referenced from this PR).
